### ISSUE TITLE
bug: Matching cap not being applied

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#1039]
**Overview**
The matching calcs generated for three of our alpha rounds do not have the matching cap applied. You can see all the current results [outlined in this sheet](https://docs.google.com/spreadsheets/d/1cvGCZelqywun_rV2BlkCQJ8eRSVtoOMZZLwMtapuEy4/edit#gid=373865926). 

UNICEF is correct but the other three do not have their caps applied:
- [ ] Fantom is supposed to be 10% but has one project >20%
- [x] Optimism Simulated is supposed to be 20% but has one project >20%
- [x] Mainnet Simulated is supposed to be 20% but has two projects >20%

**Comment by thelostone-mc** [comment]
**Simulated Mainnet**

http://localhost:8000/api/v1/update/match/round/1/0xff519cf66c0ef800dcd32c92be89841859348fd6

![Image](https://user-images.githubusercontent.com/5358146/214329895-3a03e69c-3c3c-458d-8e68-42645eda1021.png)

**Comment by thelostone-mc** [comment]
**Simulated Optimism**

http://localhost:8000/api/v1/update/match/round/10/0x568a17a8de88cc5f3f443aa4f4e3b67ccaa80505



![Image](https://user-images.githubusercontent.com/5358146/214344312-d4d14bcc-aad0-4847-b55f-3a824df9536e.png)
