### ISSUE TITLE
spike: cache the requests to the passport scorer  from grant-explorer and api

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#1055]
### Description

Are we able to cache the requests to the passport scorer more intelligently from the Grant Explorer.
In the current implementation , the grant explorer adds extra pressure on the node as we make passport calls every time on page load. The goal of this task is come up with a possible caching solution to help us ensure we don't DOS the passport endpoint

A similar solution would have to be implemented for the API package as we'd end up invoking the bulkd endpoint each time we run the calculations and that is a heavy call

**Comment by thelostone-mc** [comment]
Okie just synced up with passport team  :

- current implementation works 
- All our get score API calls go directly to the DB and not cermaic. We can cache this but Gerald said it's not required as they are adding a redis caching layer at their end.
- The same logic for the bulk api caching -> it reads from passport DB and they will have caching on it soon -> the only reason we cache it / store it locally is for faster lookups at our side. Makes no difference to passport

Additionally passport has auto scaling enabled but they've not exceeded beyond 50% of the cluster threshold 

The only point of failure in terms of DOS is where we are 
- requesting to update passport score 
- submit passport score for a community 

^ These are user triggered actions and we have timeouts between calls to check if the scoring had been complete

**Comment by nfrgosselin** [comment]
@thelostone-mc are there follow-on stories here that we should capture? Can we close out this ticket?

**Comment by thelostone-mc** [comment]
Nope we can close this out
