### ISSUE TITLE
Explorer: Donation Progress stops on step 2 but the transaction still goes through

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/grants-round#1069]
**Overview**
I'm seeing this TRANSACTION_REPLACED error in the logs. Points to the transaction being repriced due to an increase in gas fee.

**Steps To Reproduce**
No known reproduction yet. We have a sample TX: https://etherscan.io/tx/0x1b7dace8eaf33f2e14fe57458f90db835cccf727944a66d339dcf415a7dc492d in which  the user got the error but the transaction went through

**Observed  behavior**
 While donating, the user gets an error message on the frontend and the donation is stuck on the 2nd step however the transaction is successful
![image](https://user-images.githubusercontent.com/88308638/216079000-b712eb13-5b1e-4f5d-ba20-f28dc7de2688.png)

**Expected behavior**
We should not error out the transaction during a repricing

**Screenshots**
https://www.loom.com/share/9ca37644afed4ae2934e3ff71b683b60
![image](https://user-images.githubusercontent.com/88308638/216074957-cd603b7a-1ff0-47e3-ba09-94c595dcfed1.png)

**Comment by hmrtn** [comment]
This is reproducible by canceling an in progress tx.

When users change their mind after submitting a transaction, they may want to increase the gas price to get the transaction in faster, but this results in a different transaction hash. To cancel a transaction, it is possible to send a new transaction with the same nonce and a higher gas price, bribing miners to ignore the initial transaction and focus on the new one. Alternatively, users may forget about a stale transaction and make a new one with a higher gas price, effectively replacing the earlier transaction. This is ultimately the same as canceling a transaction, but less explicit.

We could open up a few tickets to handle errors more specifically - this will be resolved next deployment with handling a TRANSACTION_REPLACED error.

**Comment by hmrtn** [comment]
This does point out that we really need to start a proper error handling milestone - where we implement error codes!
