### ISSUE TITLE
bug: wrong mapping of projects contribution leads to doubled vote amount

### ISSUE THREAD

**Issue by karpovdmitryod** [gitcoinco/grants-round#1075]
**Overview**
It looks like the current logic has a bug in project contribution mapping, and due to this bug, the amount is doubled for the first contributor entry.
According to existing logic:

1) [new projectId added to mapping. It's a new entry, so new contributor added as well](https://github.com/gitcoinco/grants-round/blob/9ba40d762da9e7c58a0d67b3b81390f6c54b8fd7/packages/api/src/votingStrategies/linearQuadraticFunding.ts#L356) 
2) [contributor just added in step 1, check for new contributor returns false](https://github.com/gitcoinco/grants-round/blob/9ba40d762da9e7c58a0d67b3b81390f6c54b8fd7/packages/api/src/votingStrategies/linearQuadraticFunding.ts#L371)
3) [since projectId and contributor was just added in step 1, same amount  is added one more time to the same contributor](https://github.com/gitcoinco/grants-round/blob/9ba40d762da9e7c58a0d67b3b81390f6c54b8fd7/packages/api/src/votingStrategies/linearQuadraticFunding.ts#L379)

If this logic is intentional - can you please let me know what is the logic behind it?
thanks in advance

**Comment by nfrgosselin** [comment]
Duplicate ticket — already solved
