### ISSUE TITLE
Integrate web3 wallet framework

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#108]
**User Story:**
As a round operator
I want to connect my wallet of choice to Round Manager
So that I am not limited to only using one wallet

**Acceptance Criteria**
- Integrate ~~web3-onboard~~ wagmi.sh with Round Manager dApp

GIVEN that I am on Round Manager and my wallet **is not** connected
WHEN I click connect wallet
THEN I am served the wagmi modal for connecting my wallet

GIVEN that I am on Round Manager 
WHEN my wallet **is** connected
THEN I see the wagmi wallet bar in the top right of the nav
AND can interact with its capabilities

**Product & Design Links:**
[Miro link](https://miro.com/app/board/uXjVOo2B--w=/?moveToWidget=3458764529737721659&cot=14)

**Tech Details:**
~~web3-onboard docs: https://docs.blocknative.com/onboard~~
wagmi.sh docs: https://wagmi.sh/

the Grant Hub team started a branch on this [here](https://github.com/gitcoinco/grant-hub/tree/183-wallet-connect)

**Open Questions:**

**Notes/Assumptions:**

**Comment by shavinac** [comment]
wip branch: https://github.com/gitcoinco/grants-round/tree/108-integrate-web3onboard

**Comment by shavinac** [comment]
Blocking - due to design issues with web3onboard, we should first align with the Passport/GH teams on an alternate wallet solution we want to use
See web3onboard thread: https://discord.com/channels/562828676480237578/1001900899679088680

**Comment by thelostone-mc** [comment]
This can be unblocked as we have an understanding that we would like to use wagmi based on the discussion above

**Comment by nfrgosselin** [comment]
Unblocking per [this discord thread](https://discord.com/channels/562828676480237578/1001938490264657930) and this [GH discussion](https://github.com/gitcoinco/grants-round/discussions/213) —> we've decided to go with wagmi.sh

**Comment by nfrgosselin** [comment]
LGTM! Nice work team
