### ISSUE TITLE
spike: Investigate gas limit for batch payouts

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#1087]
**Overview**

Figure out how much gas / transactions can we do while doing a batch payout. 
We will have rounds which could have 400 projects in it. 
In situations like this 

-  can we do all 400 batch payouts via 1 transaction
- If not -> given these are ERC20 / native token transfer + 1 event being emitted -> how many can we do   

This would lay the foundation on if we can do batch payouts in one go / if we would need to do them in multiple steps

**Comment by bhargavaparoksham** [comment]
Gas units/transfer for ETH: 21000
Gas units/transfer for ERC20:  45000 (25000 to 150000)


ETH gas block limit / block is 15 million
No of ETH transfers that can be batched in a single block: 15000000/21000:  714
No of ERC20 transfers that can be batched in a single block: 15000000/45000: 333 


If we batch 200 transfers per transaction,

At 20 GWEI gas fee & 1500 ETH price

Cost for 200 ETH transfers: (200*21000)*20 = (4,200,000)*20 = 84,000,000 =   **0.084 ETH** = **126 USD**
Block space used: 4.2mil / 15 mil = 28% 

Cost for 200 ERC20 transfers: (200**45000)**20 = (9,000,000)*20 = 180,000,000 =  **0.18 ETH = 270 USD**
Block space used: 9mil /15 mil **=** 60%
