### ISSUE TITLE
spike: Investigate contract changes for payouts architecture

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#1088]
#### Description 

The goal here is to evaluate the changes needed on the contract / dapp side to support the payout milestone

**Comment by thelostone-mc** [comment]
The issues here document the changes which would have to be made : 

- https://github.com/gitcoinco/grants-round/issues/1093
- https://github.com/gitcoinco/grants-round/issues/1094
- https://github.com/gitcoinco/grants-round/issues/1095
- https://github.com/gitcoinco/grants-round/issues/1096
- https://github.com/gitcoinco/grants-round/issues/1098
- https://github.com/gitcoinco/grants-round/issues/1099
