### ISSUE TITLE
Error fetching Passport score

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#1113]
**Overview**
Passport is erroring out on [Explorer](https://grant-explorer.gitcoin.co/#/round/1/0x1b165fe4da6bc58ab8370ddc763d367d29f50ef0/passport/connect)

**Screenshots**
![image](https://user-images.githubusercontent.com/15041635/217846718-02b2edd0-3930-4e2e-9d05-076ced72bcd1.png)

**Comment by DanieleSalatti** [comment]
The Alchemy error we saw in the console was a red herring. I am now able to reproduce this, and we are getting an error back from the Passport scorer API:

`{"address": "0x523d007855b3543797e0d3d462cb44b601274819", "score": null, "status": "ERROR", "last_score_timestamp": null, "evidence": null, "error": "'credentialSubject'"}`
