### ISSUE TITLE
Provide application function in round contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#115]
**User Story:**
As a protocol user
I want to have an application function in the round contract
So that I can submit grant applications directly to the round

**Acceptance Criteria**
GIVEN that I have application data in the proper format
WHEN I call the application function in a specific round contract
THEN my application data is submitted to that round

**Tech Details**
##### When is it invoked
Project owner fills out the form  generated by the schema) -> Hub-Team upload its to IPFS ->  the invoke this new function

##### When 
invoked the new function for us to capture and log the application on-chain.

**Comment by thelostone-mc** [comment]
This would additionally require us to work with the hub team to have them share the spec on how the filled out schema would look like!

**Comment by thelostone-mc** [comment]
This would additionally require us to work with the hub team to have them share the spec on how the filled out schema would look like!

**Comment by thelostone-mc** [comment]
update: this code changes for this are ready but we still need to document on how the JSON object would look like :
- the project detail snapshot
- the filled answers

Assigning this to you @nfrgosselin and add the blocked tag
