### ISSUE TITLE
Approve / reject grant

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#145]
**User Story:**
As a round operator
I want to be able to approve or reject applications
So that I can decide whether I let a project in my round

**Acceptance Criteria**
GIVEN that I am on the application detail page
WHEN I look at the page
THEN I see an "Approve" button in the unselected state
AND I see a "Reject" button in the unselected state

GIVEN that I am on the application detail page
WHEN I click on the approve or reject button
THEN I see the confirmation modal 

GIVEN that I am on the application detail page with the confirmation modal open
WHEN I click on the Cancel button
THEN the confirmation modal closes

GIVEN that I am on the application detail page with the confirmation modal open
WHEN I click on the Confirm button
THEN the confirmation modal closes
AND the Metamask modal opens

GIVEN that I am on the application detail page with the Metamask modal open
WHEN I click confirm
THEN the application is recorded as approved or rejected (depending on the button)
AND the Metamask modal closes
AND the relevant button is shown in the selected state

**Product & Design Links:**
[Miro](https://miro.com/app/board/uXjVOo2B--w=/?moveToWidget=3458764528833032435&cot=14)

**Tech Details:**
Flow
- Get all pending review Grants from subgraph -> Take bulk action (approve / reject ) -> Upload that data to IPFS -> Emit event
- Documenting the schema of how the IPFS structure
- Allowing the subgraph to update indexes and fetch the following 
- [ ] fetch approved grants in a given round
- [ ] fetch rejected grants in a given round

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
This replaces #[#117](https://github.com/gitcoinco/grants-round/issues/117)

**Comment by thelostone-mc** [comment]
The is partially fulfilled by PR: 168

**Comment by thelostone-mc** [comment]
Blocked on this as we would need #119 to be completed and have valid metaPtr hashes

**Comment by nfrgosselin** [comment]
@thelostone-mc Tim dropped the sample IPFS here:

https://gitcoin.mypinata.cloud/ipfs/QmPLdtshZZXxyYNWhMWszvB22ssSp47K8KovZfDYZQerh9

**Comment by nfrgosselin** [comment]
Approving based on the vimeo link attached to the PR

**Comment by nfrgosselin** [comment]
@chibie couple questions shown in the screen recording [here](https://share.vidyard.com/watch/zjF8FLv3gFAjs99oi7qWPS?):

- Is the default state for a grant with both "Approve" and "Rejected" buttons unselected? It looks like all three here have already had a decision taken already
- Right after the decision goes through I'm redirected to a page with an IPFS / Fleek message (I think). Why is it doing that?

FYI there are some other UI things here that are a little funky here that I'll document in the Hi-fidelity story for this page

**Comment by nfrgosselin** [comment]
Accepting per my chat with Chibie

- Confirmed that default state is unselected
- Clarified that the second issue is a problem with Fleek overall
