### ISSUE TITLE
task: replace get program list and operators using subgraph

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#149]
**Deployed to** 
https://thegraph.com/explorer/subgraph/thelostone-mc/program-factory-v0

**Subgraph endpoints:**
https://api.thegraph.com/subgraphs/name/thelostone-mc/program-factory-v0

**Queries I've documented here:**
https://github.com/gitcoinco/grants-round/tree/main/packages/graph/docs

note: when you run the query -> make sure sure the addresses are lower case

**Comment by thelostone-mc** [comment]
This is unblocked. While the code isn't ready.
The subgraph query can now fetch metadata

```
{
  programs(first: 5) {
    id
    metaPtr {
      id
    }
  }
}
```
