### ISSUE TITLE
task: replace get round list and operators using subgraph

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#150]
**Deployed to** 
https://thegraph.com/explorer/subgraph/thelostone-mc/program-factory-v0

**Subgraph endpoints:**
https://api.thegraph.com/subgraphs/name/thelostone-mc/program-factory-v0

**Queries I've documented here:**
https://github.com/gitcoinco/grants-round/tree/main/packages/graph/docs

note: when you run the query -> make sure sure the addresses are lower case

**Comment by thelostone-mc** [comment]
This is now unblocked and you can fetch round info by doing 

```
{
  rounds(first: 5) {
    id
    roundStartTime
    roundEndTime
    roundMetaPtr {
      protocol
      pointer
    }
  }
}
```

**Comment by chibie** [comment]
@thelostone-mc can we include `ownedBy` to the query fields?

**Comment by thelostone-mc** [comment]
Yup ! Added and Deployed
