### ISSUE TITLE
Add Optimism testnet to factory deploy scripts

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#154]
**User Story:**
As a Round Manager engineer
I want a script to deploy the RM factory contracts to Optimism Kovan
So that I can consistently deploy the factory contracts

**Acceptance Criteria**
- update deploy scripts to deploy factories on Optimism Kovan
- share link to factory contract on Optimism block explorer
- create documentation for updating deploy scripts

**Product & Design Links:**

**Tech Details:**
- Review [deploy steps here](https://github.com/gitcoinco/grants-round/blob/main/packages/contracts/docs/DEPLOY_STEPS.md)

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Moving this to blocked as https://kovan-optimistic.etherscan.io/ sign up is not working. 
unable to verify contracts

**Comment by nfrgosselin** [comment]
LGTM
