### ISSUE TITLE
Create Program Page operators fields overwrite each other

### ISSUE THREAD

**Issue by pragmatriot** [gitcoinco/grants-round#176]
**Overview**
Currently, when I am on the Create Program page, when I try to add multiple operators, whatever field is being typed into overwrites the value in the other fields when trying to save the Program.

**Steps To Reproduce**
1. Go to `/program/create`
2. Enter a name
3. Add multiple operators with different addresses
4. Click `Save`

**Observed  behavior**
All operator fields change to the last value entered for an operator address

**Expected behavior**
The operator values remain as entered

**Additional context**
It looks like there was already some code added to address this, but no story in the backlog references this issue.

https://github.com/gitcoinco/grants-round/blob/dded4eda6075c08c19b8b81f3d55a999dbe10a01/packages/round-manager/src/features/program/CreateProgramPage.tsx#L147-L148

**Comment by nfrgosselin** [comment]
LGTM!
