### ISSUE TITLE
chore: verify deployed contracts on optimism kovan

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#183]
The goal of this task is to ensure all the contracts we have deployed on Kovan Optimism is verified on etherscan
The contracts are deployed and documented as a part of https://github.com/gitcoinco/grants-round/pull/181

This task would require:
- creating an account on optimism etherscan 
- wire in etherscan API key 
- verify the Factory and Implementation contract

**Comment by thelostone-mc** [comment]
This is blocked as optimism etherscan sign up flow is failing.

**Comment by codenamejason** [comment]
do you need a key? I have one for OP.

**Comment by QEDK** [comment]
> do you need a key? I have one for OP.

@thelostone-mc you want to try verification with Jason's key?

**Comment by thelostone-mc** [comment]
Yes pleaseee @codenamejason  <3 
I WILL BUY YOU 🍻 FOR HELPING ME OUT HERE :D

**Comment by thelostone-mc** [comment]
Closing this out as the contracts have been verified:

- ProgramFactory: https://kovan-optimistic.etherscan.io/address/0xb19589C32351EC32652BAb386b61443b741B678a
- ProgramImplementation: 
- Program: https://kovan-optimistic.etherscan.io/address/0x857e76d3E83f087c7BA18d03A8d7488fbE52DA1B

- RoundFactory: https://kovan-optimistic.etherscan.io/address/0xbB8f276FE1D52a38FbED8845bCefb9A23138Af92
- RoundImplementation: https://kovan-optimistic.etherscan.io/address/0xc76Ea06e2BC6476178e40E2B40bf5C6Bf3c40EF6
- Round: https://kovan-optimistic.etherscan.io/address/0x3Cd6edA7fDF9ab6b6AF6E226Ce184569C5DF8Ae5
- BulkVoting: https://kovan-optimistic.etherscan.io/address/0x2D39988C462C63b0035c3824fDEE80938cB27d0b

**Comment by thelostone-mc** [comment]
Thanks for the help here guys <3
