### ISSUE TITLE
View approved applications

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#187]
**User Story:**
As a round operator
I want to see the applications that I have approved for my round
So that I know who is eligible for funding in my round

**Acceptance Criteria**
GIVEN that I am on the round detail page
WHEN the Applications toggle is in the "Approved" state
THEN I only see the details of grants that have been approved for my round

**Product & Design Links:**
[Miro link](https://miro.com/app/board/uXjVOo2B--w=/?moveToWidget=3458764529736897818&cot=14)

**Tech Details:**
[Query docs](https://github.com/gitcoinco/grants-round/blob/main/packages/graph/docs/Round.md)

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Could we add why this is blocked ?

**Comment by nfrgosselin** [comment]
Hey @chibie —> I'm not seeing the approved or rejected applications on those tabs ([see this clip](https://share.vidyard.com/watch/FUoubdckq3EnKTtECeN9Dx?)) Can you take another look?

**Comment by chibie** [comment]
hey @nfrgosselin,

this is because of a bug with the subgraph failing to update the status of a grant... i already notified @thelostone-mc and he's working on it.

approved/rejected applications will show up once the bug is fixed.

**Comment by nfrgosselin** [comment]
Just saw the fix — looks good! Thanks @chibie
