### ISSUE TITLE
View rejected applications

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#188]
**User Story:**
As a round operator
I want to see the applications that have been rejected from my round
So that I can verify who has been rejected

**Acceptance Criteria**
GIVEN that I am on the round detail page
WHEN the Applications toggle is in the "Rejected" state
THEN I only see applications that have been rejected

**Product & Design Links:**
[Miro link](https://miro.com/app/board/uXjVOo2B--w=/?moveToWidget=3458764529736897818&cot=14)

**Tech Details:**
[Query docs](https://github.com/gitcoinco/grants-round/blob/main/packages/graph/docs/Round.md)

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Could we add why this is blocked ?

**Comment by nfrgosselin** [comment]
LGTM!
