### ISSUE TITLE
add 404 page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#200]
**User Story:**
As a round operator
I want to see the high-fidelity design for Round Manager
So that I can trust the dApp

**Acceptance Criteria**
GIVEN that I am on the Round Manager dApp
WHEN I get a 404 error
THEN I see the updated 404 page design

**Product & Design Links:**
[Design](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=80%3A1672)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
@thelostone-mc Is there a way for me to reproduce the 404 page? I tried entering in random urls but I get a fleek error

**Comment by thelostone-mc** [comment]
https://rmgitcoin.on.fleek.co/#/unicorn 
Should throw up the 404 page

**Comment by nfrgosselin** [comment]
Great, thanks!
