### ISSUE TITLE
test: create front-end component testing pattern

### ISSUE THREAD

**Issue by pragmatriot** [gitcoinco/grants-round#210]
The work to enable TDD on RTK-wrapped components is non-trivial, so we are creating a separate story to track getting that set up. Currently, we added some [MSW](https://mswjs.io/) setup in #135 to stub responses and use a real RTK stack, but we should invest time to figure out how to make this more dynamic/changeable for each test.

**Acceptance Criteria**
- Component pattern for 1 component
- Documentation of pattern / reproduction directions

**Comment by pragmatriot** [comment]
@chibie Here's the story we talked about

**Comment by thelostone-mc** [comment]
Quick call out : let's ensures stories are added to the backlog during IPM.
we still want the team / product to help us align here

cc @nfrgosselin could we look into getting this for next IPM ?

**Comment by chibie** [comment]
https://medium.com/@johnmcdowell0801/testing-rtk-query-with-jest-cdfa5aaf3dc1

**Comment by pragmatriot** [comment]
Adding blocked label until front-end API testing pattern is established to prevent duplicate work/code

**Comment by pragmatriot** [comment]
Work for this is currently on the branch `210--frontend-component-testing`

**Comment by thelostone-mc** [comment]
@pragmatriot Could you open up a PR for this
