### ISSUE TITLE
Verify verified credentials

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#212]
**User Story:**
As a round operator
I want to know if a project's social accounts have been verified
So that I know whether I can trust the application

**Acceptance Criteria**
GIVEN that a project has submitted social accounts in their application
WHEN I look at the social account at the top of the application details page
THEN I see whether the social account is verified

**Product & Design Links:**
[Figma link to designs](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=84%3A1040)

**Tech Details:**
- verify that the VC is actually sent from IAM server
- check that the issuer is the same as one who signed it
-  the round manager should be able to verify the credential with [something like this](https://github.com/schultztimothy/passport-sdk/blob/28e9fc8daf478eb965eb4fecd4f883171b87f561/examples/example-nextjs-passport-sdk-verifier/pages/index.js#L93) 
- example VCs [here](https://discord.com/channels/562828676480237578/1006330978047885352/1006961874190999664)
- How can RM check if the VC actually belongs to the project?
Check that the Twitter username / GitHub org name in the VC `credentialSubject.provider` matches the project's twitter/github. Eg "ClearTextGithubOrg#**MyGithubOrg**#MyGithubUserId" / "ClearTextTwitter#**MyTwitterUsername**"
Check that the `credentialSubject.id` matches one of the project owners' addresses, see [discord message](https://discord.com/channels/562828676480237578/1009585109697056889/1009837475021193256) for retrieving owners

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Acceptance notes:**
A "valid" VC means that:
1. VC is cryptographically sound - the signature in the VC matches the content of the VC
2. The VC is issued by the IAM server, and the IAM server was the entity that signed the VC
3. The social account names claimed in the VC matches the account names provided by the project's grant application
4. The VC `credentialSubject` corresponds to one of the project owners

For this story we can implement checks for conditions 1, 2, and 3 with the information we currently retrieve about a project/application.
To implement a check for condition 4, Round Manager will need to retrieve Project Owner information - this will be done in #290

**Comment by dschinkel** [comment]
@pragmatriot and @dschinkel: we weren't able to run tests due to Jest not able to compile .wasm files:

> Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Did a good amount of research and we'll need to regroup and talk about this.  Some possible options:

1. Is there anything other than [spruceid/didkit](https://github.com/spruceid/didkit) that we could use to verify credentials for web3?
1. If no, might have to re-architect the config
  * eject & use webpack 4 (but then this is no longer supported if we used after ejecting https://github.com/ballercat/wasm-loader)
  * create-react-app doesn't support Webpack 5 yet.  So we could remove create-react app & create custom config using Webpack 5 (and then webpack 5 supports WebAssembly natively)
1. Build a rust service that can verify credentials that react app can call?

**Comment by dschinkel** [comment]
Moved to blocked because we need to have a team discussion on the above comment

**Comment by shavinac** [comment]
create-react-app 5.x.x supports webpack 5 though
https://github.com/facebook/create-react-app/releases/tag/v5.0.0

**Comment by pragmatriot** [comment]
Following Shavina's comment above, we ultimately unblocked ourselves on this story. Moved back to in-progress.

**Comment by shavinac** [comment]
Is it possible to "lie" on applications, and how should RM handle this?

Example:
Nate creates a new project through Grant Hub, and goes through the GitHub and Twitter verification process for his NateGithubOrg and NateTwitter accounts. Nate's project metadata is uploaded to IPFS.

Evil Eve creates & uploads her own IPFS document which copies the GitHub and Twitter VCs from Nate's project metadata into her own, falsely claiming that she has verified those accounts.

The VCs on Eve's metadata are still cryptographically valid, so RM would need some way to verify that the VC was issued to a specific project...

**Comment by shavinac** [comment]
@nfrgosselin @Etovardesign if the verifiable credential is provided in the application but is NOT valid (expired, issued to incorrect project, tampered with, etc), should we display anything? Like an ❌ instead of ✅ ?

**Comment by nfrgosselin** [comment]
This LGTM — there was a slight delay between my application appearing and the verified icon showing with my Twitter username. I have a feeling this was because of the query time so I'd love for us to better understand query times on the app — I'll bring this up in our next tech retro
