### ISSUE TITLE
Add footer to app

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#217]
**Overview**
Adding the footer from the hi-fidelity designs to the page (retroactive ticket for PR #215)

**Comment by nfrgosselin** [comment]
@thelostone-mc I'm not seeing the footer on the test app right now — can you take another look?

**Comment by nfrgosselin** [comment]
hey @thelostone-mc, bumping this — have you looked at this again?

I just saw it on the round creation flow but it's covered by the form builder
![Image](https://user-images.githubusercontent.com/15041635/183083471-d725e8a7-c02a-4258-b567-dc7f988d60bc.png)

**Comment by thelostone-mc** [comment]
The footer was integrated only on the main page. Lemme reopen and add it to all pages

**Comment by nfrgosselin** [comment]
@thelostone-mc I'm still seeing the same issue on round creation flow page — do you know why this is still happening?

**Comment by thelostone-mc** [comment]
@nfrgosselin https://github.com/gitcoinco/grants-round/pull/273 should fix it. Has a screenshot of the same page.
Looks like it was an issue with the page and not the navbar

**Comment by nfrgosselin** [comment]
LGTM — thanks @thelostone-mc
