### ISSUE TITLE
Add encryption boolean to round metadata

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#221]
**User Story:**
As a RM engineer
I want to pass encryption information in my application schema
So that Grant Hub knows which fields to encrypt

**Acceptance Criteria**
- ~Public key can be deployed with round schema~
- ~Encryption details are added to round application schema~
- Make it possible to add encrypt as a boolean to every question. default it to false
- Ensure when the application schema is updated , the documentation is updated as well 
- For MVP, email is the only field which should be encrypted 

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Yo to whoever picks this ticket. I've got a WIP progress #238 
And looking at it , we likely don't have to add the public key to IPFS

This means the story would now be updated to :
Ensure we update the schema to just add encrypted: boolean to every question in the application schema 
We can default the value to false

Refer to the documentation over in the PR

**Comment by nfrgosselin** [comment]
LGTM
