### ISSUE TITLE
test: create front-end API testing pattern

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#240]
Create tests for front-end APIs

### Notes
This likely involves using MSW to mock out GraphQL and IPFS requests

**Comment by shavinac** [comment]
WIP branch with an example for IPFS saveToIPFS API - `240--rtk-api-testing`

**Comment by shavinac** [comment]
blocked until tech retro

**Comment by shavinac** [comment]
Closing - see https://github.com/gitcoinco/grants-round/issues/298 for spike using React Context instead of Redux/RTK Query - new stories will be created based on the discussion/outcome of that spike
