### ISSUE TITLE
Deploy UI to production

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#241]
## Description

The goal of this task is to 
- create a new release branch 
- set up auto deploy to env via fleek ( explore if we have a shared team on fleek we can use) 
- document on how we would release changes to live 
- discuss with product and finalize hosting name 

At the end of it, we should have a staging env ( already setup ) and am actual live env

**Comment by thelostone-mc** [comment]
Blocked cause we need card to setup a paid account.
https://discord.com/channels/562828676480237578/968479541142093834/1009000372058202202
Following up on that on the above thread

**Comment by nfrgosselin** [comment]
LGTM! we're live 🎉
