### ISSUE TITLE
Add Datadog monitoring

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#242]
## Description 

The goal of this task is to sync with passport team and implement 
- datadog monitoring 
- document on how to use it 
- share knowledge from the team 

Since this is the first time we are adding monitoring to a fully decentralised product, we need to be sure of where to look / how to debug.

**Comment by thelostone-mc** [comment]
Waiting on team to decide if we should have a shared account / have an indepenent account 
https://discord.com/channels/562828676480237578/968479541142093834/1009009619152162886

**Comment by thelostone-mc** [comment]
The decision is to use the same account ! This should be unblocked
