### ISSUE TITLE
Handle invalid URL parameter errors

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#243]
**User Story:**
As a round operator
I want to be redirected to appropriate error pages
So that I know how to troubleshoot issues

**Acceptance Criteria**
- If program not found on program detail page -> redirect to 404
- If round not found on round detail page -> redirect to 404
- If application not found on application detail page -> redirect to 404

~~GIVEN that I am on Round Manager AND my wallet is connected~~
~~WHEN I try to access a page with an invalid parameter~~
~~THEN I see the 404 page~~

~~GIVEN that I am on Round Manager AND my wallet is not connected~~
~~WHEN I try to access a page~~
~~THEN I see the main RM page with connect wallet button~~

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Could you explain with an example here ? 
Me trying to understand what qualifies as a 404 vs access denied page in our app

**Comment by thelostone-mc** [comment]
I believe this app already works this way:


https://rmgitcoin.on.fleek.co/#/program/0x51184b429edbcdc5ca5f60c69467a45d50e2c482 with connected wallet shows page.
https://rmgitcoin.on.fleek.co/#/program/0x51184b429edbcdc5ca5f60c69467a45d50e2c482 without a wallet connected redirects user to home page with connect wallet button

[Invalid routes --->  404 :](https://rmgitcoin.on.fleek.co/#/program/0x51184b429edbcdc5ca5f60c69467a45d50e2c482)
- https://rmgitcoin.on.fleek.co/#/beep
- https://rmgitcoin.on.fleek.co/#/random
- https://rmgitcoin.on.fleek.co/#/pop


![Image](https://user-images.githubusercontent.com/5358146/185544863-0a0254f0-6dc3-4182-b5eb-b7ade2faa711.gif)

**Comment by thelostone-mc** [comment]
synced with @chibie ! 

@nfrgosselin this can be updated to say:

- If program not found on program detail page -> redirect to 404
- If round not found on round detail page -> redirect to 404
- If application not found on application detail page -> redirect to 404

**Comment by nfrgosselin** [comment]
thanks @thelostone-mc / @chibie  — updated!

**Comment by nfrgosselin** [comment]
LGTM
