### ISSUE TITLE
chore: add documentation for contracts

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#244]
Integrate [primitive-dodoc](https://github.com/primitivefinance/primitive-dodoc) to generate docs for our contracts 

Refer convo in: https://discord.com/channels/562828676480237578/962026258273804398/992125870863040512

**Comment by thelostone-mc** [comment]
This was fixed up using 545a0cb as I had set it up while playing around with it and forgot to get it done
