### ISSUE TITLE
Use of concatenated string in ByteArray.fromHexString potentially causing subgraph indexing failure

### ISSUE THREAD

**Issue by DanieleSalatti** [gitcoinco/grants-round#246]
https://github.com/gitcoinco/grants-round/blob/0163beb16ce987aca4704e2c39c0ecdfa0af6697/packages/graph/src/utils.ts#L11-L13

`fromHexString` requires the input to consist of an even number of elements:

https://github.com/graphprotocol/graph-ts/blob/55545f3d39b1c6b78e7d96aa83cc2692b8e2ae33/common/collections.ts#L69-L85

Concatenating with `-` will eventually cause it to be odd, resulting in the following error when indexing the subgraph:

```
Subgraph instance failed to run: Mapping aborted at
~lib/@graphprotocol/graph-ts/common/collections.ts, line 75, column 5, with message:
input 0x10-0x7a67063c391f266d31ea6c9ec7c788c1323b7746
has odd length wasm backtrace: 0: 0x33a6 - <unknown>!src/utils/generateID 
1: 0x3779 - <unknown>!src/projectregistry/implementation/handleProjectCreated
in handler `handleProjectCreated` at block #7290664
(7e55868b57914676aff8a77bc26bf0187d30cfa707b7bb0990217be6e6687a2e),
code: SubgraphSyncingFailure
```

**Comment by thelostone-mc** [comment]
The subgraphs have been re-deployed with this change across all networks @DanieleSalatti
