### ISSUE TITLE
Add bulk approval buttons

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#251]
**User Story:**
As a round operator
I want to be able to bulk approve (or reject) applications
So that I don't have to pay gas fees for every application approval

**Acceptance Criteria**
GIVEN that I am on the round details page AND I have received applications
WHEN I look above the application cards
THEN I see the Select button and associated copy

GIVEN that I am on the application details page and have received applications
WHEN I click on the "Select" button
THEN the bulk approval buttons appear on each application card
AND every bulk approval button is in the "unselected" state
AND the text of the "Select" button changes to "Cancel"

GIVEN that I am on the application details page and can see the bulk approval buttons
WHEN I click on the "Cancel" button
THEN the bulk approval buttons disappear
AND the text of the button changes back to "Select"

GIVEN that I am on the application details page and can see the bulk approval buttons
WHEN I click an unselected button on an application card
THEN that button is set to the "selected" state
AND that card's other bulk approval button is set to the "unselected" state

GIVEN that I am on the application details page and have selected one of an application card's bulk approval buttons
WHEN I click a selected button
THEN the button is set to the "unselected" state

**Product & Design Links:**
bulk approval select button
![Image](https://user-images.githubusercontent.com/15041635/183440481-28814fca-8b37-4c2f-96f5-09936c68beb3.png)

bulk approval buttons (all unselected)
![image](https://user-images.githubusercontent.com/15041635/183127913-6d03fa1a-e4bb-4fe2-920a-6b58ff8e58be.png)

bulk approval buttons (with selected states)
![image](https://user-images.githubusercontent.com/15041635/183127957-81c1e9eb-5bf0-4695-a93c-1c1455841937.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by chibie** [comment]
this ticket depends on #249

**Comment by nfrgosselin** [comment]
LGTM! Nice work
