### ISSUE TITLE
Confirm bulk approval decisions

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#252]
**User Story:**
As a round operator
I want to be able to bulk approve (or reject) applications
So that I don't have to pay gas fees for every application approval

**Acceptance Criteria**
GIVEN that I am on the round details page and can see the bulk approval buttons
WHEN at least one bulk approval button is selected
THEN I see the "Continue" button 
AND I see copy that says "You have selected _N_ grant applications" (where _N_ is the number of cards with selected buttons)

GIVEN that I am on the round details page and have selected at least one bulk approval button
WHEN I click the "Continue" button
THEN I see the Confirmation State modal with the correct number of selected applications

GIVEN that I am on the round details page and can see the Confirmation State modal
WHEN I click "Confirm"
THEN the wallet signature flow is triggered

GIVEN that I am on the round details page and can see the Confirmation State modal
WHEN I click "cancel"
THEN the modal closes
AND the applications that were selected are still in their selected state

GIVEN that I am on the round details page and have triggered the bulk approval wallet signature
WHEN the signature completes
THEN the selected applications are assigned their new status
AND the bulk assigned applications are moved to the correct tabs
AND I am returned to the "Received" tab 

**Product & Design Links:**
Selected cards with "continue" button
![image](https://user-images.githubusercontent.com/15041635/183129579-25530395-b076-4a7f-846d-b709c00a9e41.png)

Confirmation state modal
![image](https://user-images.githubusercontent.com/15041635/183129634-d40a6b92-496c-4417-b89d-633ec936db5b.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
depends on #251

**Comment by nfrgosselin** [comment]
Overall this LGTM — the only issue is that the placement of the Continue button doesn't look right. Can we fix that?

![Image](https://user-images.githubusercontent.com/15041635/184728022-01bd2420-28c8-4a2c-9fef-f8b447149324.png)

**Comment by thelostone-mc** [comment]
@shavinac what's the best way for me to see how we did those changes for my understanding ?

**Comment by shavinac** [comment]
> feat: confirm bulk approval #271

Currently `main` branch protection rules are still in place, so we are still using PRs at the moment. The PR linked to this issue is https://github.com/gitcoinco/grants-round/pull/271

**Comment by shavinac** [comment]
> Overall this LGTM — the only issue is that the placement of the Continue button doesn't look right. Can we fix that?

Thanks for catching that! Addressed in #283
