### ISSUE TITLE
task: take TDD pass on wallet components

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#262]
**Acceptance Criteria**
Review following components and add in TDD where applicable:
* ~~wallet connection flow~~ (handled by rainbow)
* ~~wallet display component~~ (handled by rainbow)
* Auth page

**Comment by thelostone-mc** [comment]
Calling out cause once we setup rainbow-toolkit. I believe this might be redundant

**Comment by thelostone-mc** [comment]
Tagging @chibie / @dschinkel to check and confirm if this story can be removed after the migration to rainbow-toolkit

**Comment by chibie** [comment]
i think it might still be relevant to write test for the Auth component @thelostone-mc

**Comment by nfrgosselin** [comment]
Consolidated into refactor ticket [#104](https://github.com/gitcoinco/grants-round/issues/104)
