### ISSUE TITLE
Update application configuration page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#274]
**User Story:**
As a round operator
I want to see the list of information that I'll receive from applicants
So that I can plan for my review process

**Acceptance Criteria**
- Application configuration page is the [new design](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=902%3A5849)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by chibie** [comment]
@nfrgosselin was "Team Size" remove from the design intentionally?

**Comment by nfrgosselin** [comment]
Hey @chibie — overall this looks good but the socials are in the wrong spot. They should be in the project details section

Current / incorrect version:
![Image](https://user-images.githubusercontent.com/15041635/187918870-220cf72c-4962-42c0-8e86-921bd7386f99.png)

Correct version:
![Image](https://user-images.githubusercontent.com/15041635/187918944-8ef33a5a-8fd8-47ab-ab4d-45eeca86beb5.png)

**Comment by nfrgosselin** [comment]
LGTM — thanks!
