### ISSUE TITLE
Add application processing state to dApp

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#276]
**User Story:**
As a round operator
I want to know when application decisions are processing
So that I don't try to trigger another application decisions

**Acceptance Criteria**
GIVEN that a round operator on my round has triggered an application decision
WHEN that decision transaction is in progress
THEN the entire round (for all operators) is in the processing state

GIVEN that a round operator on my round has triggered an application decision
WHEN that decision transaction is completed
THEN the entire round (for all operators) is no longer in the processing state

GIVEN that the round is in the processing state
WHEN I am on the application detail page
THEN I see the processing bar instead of the approve/reject buttons

GIVEN that the round is in the processing state
WHEN I am on the round detail page
THEN I see the processing bar instead of the bulk approval option

**Product & Design Links:**
[Application detail page with processing bar](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=902%3A5654)
[Round detail page with processing bar](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=922%3A5561)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by chibie** [comment]
@nfrgosselin there's a couple of concerns on this ticket

1.
> GIVEN that a round operator on my round has triggered an application decision
WHEN that decision transaction is in progress
THEN the entire round (for all operators) is in the processing state

if a round operator has to wait for the completion of another operator's review, this makes the review process synchronous, shouldn't multiple round operators work simultaneously since some blockchain transactions could take hours/days to complete?

2. 
> GIVEN that the round is in the processing state
WHEN I am on the application detail page
THEN I see the processing bar instead of the approve/reject buttons

if one application which was reviewed on the detail page is processing, does that mean the whole round is in a processing state and vice versa?

**Comment by chibie** [comment]
we need a way to fetch pending/unconfirmed transactions on ethereum without subscribing to websockets.

i've tried and discovered the following,

* querying the events of the round contract address -> events are only triggered for confirmed transactions
* query the logs of the contract address with etherscan api -> doesn't return pending logs
* query using etherscan transactions api -> doesn't support pending transactions

=========

i'd move this ticket to blocked until we're able to build a centralized service to do the following:

* subscribe via websockets to fetch pending txns in mempool
* filter incoming received txns by the round contract address or method id of `updateMetaPtr((uint256,string))`
* persist data in a database

**Comment by thelostone-mc** [comment]
@chibie I would recommend creating a separate ticket to show processing state for all round operators in a given round.
Instead we rewrite this ticket to ensure we show the processing state for the operator which made the decision to approve / reject

**Comment by nfrgosselin** [comment]
I'm deprecating this ticket as we've decided to implement https://github.com/gitcoinco/grants-round/issues/395 instead
