### ISSUE TITLE
feat: kinder click areas

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#277]
**User Story:**
As a round operator
I want to have easier click areas on cards and rows
So that it is easier to navigate the dApp

**Acceptance Criteria**
GIVEN that I am on the My Programs page
WHEN I click anywhere on a specific program's card
THEN I am brought to that program's program details page

GIVEN that I am on the program details page
WHEN I click anywhere on a specific round's row
THEN I am brought to that round's round details page

GIVEN that I am on the round details page
WHEN I click anywhere on a specific application's card
THEN I am brought to that application's application detail page

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
@thelostone-mc Overall this looks great! I did have one issue with the application cards though —> for some reason one specific card didn't have a kinder click area, even though other cards in the same round did. You can see t[he video here](https://share.vidyard.com/watch/DUebUF78ZMRbTd4oG6Uyvw?)

The round is https://rmgitcoin.on.fleek.co/#/round/0x37a11131a51a5b3f23d3f368cb012db656989ac7

**Comment by thelostone-mc** [comment]
> Bulk select was no longer possible as every area of the application card is linked to the detail page. This PR makes only the card content area clickable

This was changed due to : https://github.com/gitcoinco/grants-round/pull/285

**Comment by nfrgosselin** [comment]
LGTM
