### ISSUE TITLE
set plain/default banner and logo image on applications without images

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/grants-round#278]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN an application for a project without a banner image
WHEN the round operator is viewing the application card on the round or on the application detail page
THEN the round operator should see a default image for the banner

GIVEN an application for a project without a logo image
WHEN the round operator is viewing the application card on the round or on the application detail page
THEN the round operator should see a default image for the logo

**Product & Design Links:**
- image file TBD (@Etovardesign )

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
https://discord.com/channels/562828676480237578/1006662757883592836/1021463154900873316

**Comment by shavinac** [comment]
my bad, re-opened the wrong issue

**Comment by lthrift** [comment]
I've accepted this one
