### ISSUE TITLE
Program access control

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#281]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN that I am on Round Manager AND my wallet is connected
WHEN I try to view the program details of a program to which I don't have access
THEN I see the No Access page

**Product & Design Links:**
[No Access page design](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=939%3A5674)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Building it as part of changes in [NotFound](https://github.com/gitcoinco/grants-round/issues/243) rendering as this had to be taken into account while adding the conditional rendering

**Comment by nfrgosselin** [comment]
This isn't working for me — I see the access denied screen but then it quickly flips to the 404 page:

https://share.vidyard.com/watch/NFdVQT1AMgGEP4xoaQa1GP?

**Comment by thelostone-mc** [comment]
Hmm that's cause we fetch the programs by the users logged in wallet address. We should look to change that but this might mean updating the ProgramContext API we just rewrote. Will bring this up on standup

**Comment by shavinac** [comment]
See this https://github.com/gitcoinco/grants-round/pull/297#discussion_r954334536 on the original 404/no-access pr

it should be straightforward to make the same change to ProgramContext `listProgram` api (`packages/round-manager/src/features/api/program.ts`) to allow program lookup by id without address, same as the query in `packages/round-manager/src/features/api/services/program.ts`

**Comment by shavinac** [comment]
have some notes in [281--fix-program-access-control-context ](https://github.com/gitcoinco/grants-round/tree/281--fix-program-access-control-context) branch ([diff](https://github.com/gitcoinco/grants-round/compare/281--fix-program-access-control-context)) on how we could add this into Program Context -- it's a very rough draft so please reach out to me for info :)

**Comment by nfrgosselin** [comment]
LGTM — thank you!
