### ISSUE TITLE
Update My Programs aesthetics

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#292]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
On My Programs page:
- Icons should be grey-500
- bottom background color should be #F3F3F5

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by t-proctor** [comment]
Hello, was wondering if this story was still available? If so, I had questions regarding the bottom background and colors. They are in the image below. Thank you!

<img width="515" alt="Screen " src="https://user-images.githubusercontent.com/28866303/187773995-6e954e93-764b-4f9a-a684-ff9334376193.png">

**Comment by thelostone-mc** [comment]
Oh yeah this is still up for grabs! 
We'll update the ticket with an image to be able to point exactly which icons / background we are talking about

**Comment by nfrgosselin** [comment]
Hey thanks for picking this up @t-proctor! 

The icon that needs the color change is that white "refresh" icon in the green box —> we need to change it from white to grey 500

And yes, exactly right on the bottom background —> that's the space that we want to be #F3F3F5 on every card

LMK if you have any other questions!

**Comment by t-proctor** [comment]
> Hey thanks for picking this up @t-proctor!
> 
> The icon that needs the color change is that white "refresh" icon in the green box —> we need to change it from white to grey 500
> 
> And yes, exactly right on the bottom background —> that's the space that we want to be #F3F3F5 on every card
> 
> Feel free to assign the ticket to yourself if you end up working on it.
> 
> LMK if you have any other questions!

Thank you! I don't know if I have assignment permissions, but I made a PR for it

**Comment by nfrgosselin** [comment]
LGTM!
