### ISSUE TITLE
spike: mob on react context

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#298]
**Overview**
- Implement a feature using React Context + GraphQL/REST client, instead of using RTK queries
- Suggested features to start with: list programs, create a program
- **Outcome: decide whether or not to continue React Context refactor**

**Details**
- write a test for an affected component (eg my programs page) to prove out testing strategy

Questions to answer:
- Can we maintain feature parity for users?
- Is there anything that would block current or future planned features?
- Can we write component tests and api tests that we are confident in?

**Comment by shavinac** [comment]
Resolution:
Yes, we will continue React Context refactor
Devs to wrap up spike replacing "ListPrograms" and merging, setting a pattern for remaining refactors
@shavinac to create stories for migrating each RTK query to use Context instead
