### ISSUE TITLE
Bulk approve buttons not showing up on Approved/Rejected applications

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#299]
**Observed  behavior**
Approve/Reject buttons not showing up on cards when you hit select, when in the Approved/Rejected tabs

**Expected behavior**
Approve/reject buttons should be visible on every card

- Already approved applications can only be changed to rejected
- Already rejected applications can only be changed to approved
- Each tab should be treated as separate bulk selection flows, at least for now until the UX of cross-tab selection is thought thru

**Screenshots**
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/15041635/185959674-22194102-df32-43cd-aefd-8c5e8122c486.png">

**Comment by thelostone-mc** [comment]
Closing as this feature works as expected. Discussion can be found at 
https://discord.com/channels/562828676480237578/1010273970261598238/1011555371355226182

**Comment by shavinac** [comment]
Closing this bug ticket. The bugfix will be resolved with two new stories, implementing behavior in Approved tab and Rejected tab respectively: #303 #304
