### ISSUE TITLE
Bulk reject Approved applications

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/grants-round#303]
Partially fixes this bug: https://github.com/gitcoinco/grants-round/issues/299
The rest of the bugfix will be implemented in #304 

**User Story:**
As a round operator
I want to be able to bulk reject applications in the Approved tab
So that I don't have to pay gas fees for every application decision

**Acceptance Criteria**
GIVEN that I am on the round details page AND on the Approved tab AND I have approved applications
WHEN I look above the application cards
THEN I see the Select button and associated copy

GIVEN that I am on the application details page AND on the Approved tab AND I have approved applications
WHEN I click on the "Select" button
THEN the bulk rejection buttons appear on each application card
AND every bulk rejection button is in the "unselected" state
AND the text of the "Select" button changes to "Cancel"

GIVEN that I am on the application details page and can see the bulk rejection buttons
WHEN I click on the "Cancel" button
THEN the bulk rejection buttons disappear
AND the text of the button changes back to "Select"

GIVEN that I am on the application details page and can see the bulk rejection buttons
WHEN I click an unselected rejection button on an application card
THEN that rejection button is set to the "selected" state

GIVEN that I am on the application details page and have selected one of an application card's bulk rejection buttons
WHEN I click a rejection button
THEN the button is set to the "unselected" state

GIVEN that I am on the round details page AND on the Approved tab AND can see the bulk rejection buttons
WHEN at least one bulk rejection button is selected
THEN I see the "Continue" button
AND I see copy that says "You have selected N grant applications" (where N is the number of cards with selected buttons)

GIVEN that I am on the round details page AND on the Approved tab AND have selected at least one bulk rejection button
WHEN I click the "Continue" button
THEN I see the Confirmation State modal with the correct number of selected applications

GIVEN that I am on the round details page and can see the Confirmation State modal
WHEN I click "Confirm"
THEN the wallet signature flow is triggered

GIVEN that I am on the round details page and can see the Confirmation State modal
WHEN I click "cancel"
THEN the modal closes
AND the applications that were selected are still in their selected state

GIVEN that I am on the round details page and have triggered the bulk rejection wallet signature
WHEN the signature completes
THEN the selected applications are assigned their new status
AND the bulk assigned applications are moved to the correct tabs

**Product & Design Links:**

**Tech Details:**
- Approved applications can only remain the same, or be changed to "Rejected" status. They cannot be returned to "Pending"/received, for now
- Ok for each tab to each have a separate bulk-selection flow; users cannot bulk-select "across tabs" for now

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by shavinac** [comment]
WIP branch 303--bulk-reject-approved-applications

**Comment by nfrgosselin** [comment]
Overall this looks good, but there's one issue I'd like resolved before I accept: right now when you click the "confirm" button the button doesn't update to "confirming" like on the Pending tab. I realize this is only implied in the acceptance criteria (my bad) but I think we need this to change so that it matches the other tab and gives some feedback that the transaction is in progress:

![Image](https://user-images.githubusercontent.com/15041635/188277307-58efe82a-271d-4b64-873b-d8f9833f8be8.png)

**Comment by dschinkel** [comment]
@nfrgosselin Disregard my last reply; realized it was just a small tweak, will fix that with this story.

**Comment by nfrgosselin** [comment]
LGTM!
