### ISSUE TITLE
Bulk approve Rejected applications

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/grants-round#304]
Partially fixes this bug: https://github.com/gitcoinco/grants-round/issues/299
The rest of the bugfix will be implemented in #303 

**User Story:**
As a round operator
I want to be able to bulk approve applications in the Rejected tab
So that I don't have to pay gas fees for every application decision

**Acceptance Criteria**
GIVEN that I am on the round details page AND on the Rejected tab AND I have rejected applications
WHEN I look above the application cards
THEN I see the Select button and associated copy

GIVEN that I am on the application details page AND on the Rejected tab AND I have rejected applications
WHEN I click on the "Select" button
THEN the bulk approve buttons appear on each application card
AND every bulk approve button is in the "unselected" state
AND the text of the "Select" button changes to "Cancel"

GIVEN that I am on the application details page and can see the bulk approve buttons
WHEN I click on the "Cancel" button
THEN the bulk approve buttons disappear
AND the text of the button changes back to "Select"

GIVEN that I am on the application details page and can see the bulk approve buttons
WHEN I click an unselected approve button on an application card
THEN that approve button is set to the "selected" state

GIVEN that I am on the application details page and have selected one of an application card's bulk approve buttons
WHEN I click a approve button
THEN the button is set to the "unselected" state

GIVEN that I am on the round details page AND on the Rejected tab AND can see the bulk approval buttons
WHEN at least one bulk approval button is selected
THEN I see the "Continue" button
AND I see copy that says "You have selected N grant applications" (where N is the number of cards with selected buttons)

GIVEN that I am on the round details page AND on the Rejected tab AND have selected at least one bulk approval button
WHEN I click the "Continue" button
THEN I see the Confirmation State modal with the correct number of selected applications

GIVEN that I am on the round details page and can see the Confirmation State modal
WHEN I click "Confirm"
THEN the wallet signature flow is triggered

GIVEN that I am on the round details page and can see the Confirmation State modal
WHEN I click "cancel"
THEN the modal closes
AND the applications that were selected are still in their selected state

GIVEN that I am on the round details page and have triggered the bulk approval wallet signature
WHEN the signature completes
THEN the selected applications are assigned their new status
AND the bulk assigned applications are moved to the correct tabs

**Product & Design Links:**

**Tech Details:**
- Rejected applications can only remain the same, or be changed to "Approved" status. They cannot be returned to "Pending"/received, for now
- Ok for each tab to each have a separate bulk-selection flow; users cannot bulk-select "across tabs" for now

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
LGTM!
