### ISSUE TITLE
add prettier/eslint & husky for code style

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#308]
As an engineer on the Round Manager project
I want to have Husky/Prettier/ESLint tooling added to my development cycle
So that formatting my code is less time-consuming and error-prone

```gherkin
Given that I written new code with no code style discrepancies from the agreed upon code style rules
When I try to commit it to the repository
Then I see prettier check and approve my code, allowing me to commit
AND
Given that I written new code with code style problems
When I try to commit it to the repository
Then I see prettier check my code and raise an error, stopping the commit until I fix the code style
```

For reference: [this link](https://dev.to/smetankajakub/how-to-integrate-husky-eslint-prettier-to-project-in-less-than-15-minutes-5gh)

**Comment by vacekj** [comment]
I would like to pick this up, and to avoid bikeshedding around options, just use the defaults for both prettier and eslint. Is everyone OK with that?

**Comment by nfrgosselin** [comment]
Deferring to Eng review
