### ISSUE TITLE
refactor: combine Applications(Received|Approved|Rejected) components

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#315]
These 3 components share a lot of the same code and duplicate fetching results from the same GraphQL queries as the parent component. Can be refactored into one component with props to pass data into. This would clean it up and remove its coupling with the API layer.

**Comment by vacekj** [comment]
I'm re-closing this as not implemented and deleting the issue, as this was never implemented, the PR linked wasn't merged because the changes were too outdated.
