### ISSUE TITLE
bug: fix CI logs

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#319]
> https://github.com/gitcoinco/grants-round/pull/301#issuecomment-1226886917
Looks like this PR throwing a lot of errors in console but the test pass. Could we fix it so that the tests don't reach those error state / explore a way of handling it  (not sure what would work here)

**Error 1**  (Fixed)
```
TypeError: Cannot read properties of undefined (reading 'operatorWallets')
```
This can adding operatorWallets to our mock data in the test, so should be simpler to fix

**Error 2**  (Fixed)
```
There are no focusable elements inside the <FocusTrap />
```

This log also turns up on the browser 

![Image](https://user-images.githubusercontent.com/5358146/187853266-fd1c27e0-7fd2-476e-ad59-a6879a04a096.png)

**Error 3** 

```
 FAIL  src/features/api/__tests__/program.test.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'base16')

      2 | import { isJestRunning } from './utils';
      3 |
    > 4 | const LitJsSdk = isJestRunning() ? null : require('lit-js-sdk');
```

**Comment by shavinac** [comment]
Error 1 and Error 3 fixed by PR #317

Error 2 fixed by https://github.com/gitcoinco/grants-round/pull/321
