### ISSUE TITLE
paired spike: investigate offchain tech stacks for QF calculation

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#326]
**timebox to a day**

**Overview**
The QF voting contract will need to calculate distributions based off votes and our assumption is that it will be too expensive to run those calculations on chain. We need to investigate tech stack options for the calculation so that we can begin building our infrastructure.

**Acceptance Criteria**
- Research and write recommendation on potential tech stack(s) for QF calculation
- Present recommendation to Round Manager team
- Pair with Nate to write follow-on stories

**Comment by thelostone-mc** [comment]
https://github.com/gitcoinco/grants-round/discussions/337#discussioncomment-3567645

**Comment by thelostone-mc** [comment]
Talking to QV team. We need to ack what the usecase here exactly us.

- Not every voting strategy requires us to run calculations/predictions.
- A few voting strategies can have tally run on chain  if it is computationally in-expensive

**Comment by shavinac** [comment]
[Miro board](https://miro.com/app/board/uXjVPY3Csls=/) outlining application flows for:
- Deployed App on AWS
- Flow with Scripts running on GH Actions

**Comment by thelostone-mc** [comment]
@shavinac / @dschinkel could we add summary of what we are moving ahead / why just for sake of documenting it ? 
(or do you reckon the miro board is enough ?)

**Comment by dschinkel** [comment]
@pragmatriot @shavinac @nfrgosselin meet and created some ACs today for this so closing this spike out now.

**Comment by shavinac** [comment]
> @shavinac / @dschinkel could we add summary of what we are moving ahead / why just for sake of documenting it ? (or do you reckon the miro board is enough ?)

[QF Calculation Spike Miro board](https://miro.com/app/board/uXjVPY3Csls=/), for reference

conclusion: 
- GitHub actions approach is doable, but has more unknowns/uncertainties and would require more work, for not much additional benefit at this time.
- Other decentralized computing options (e.g. other blockchains) are possible, but also requires more work for not much additional benefit
- Moving forward with centralized AWS app. Language choice TBD
