### ISSUE TITLE
paired spike: extension of voting strategy

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#327]
**timebox to a day**

**Overview**
Currently, the allocation mechanism relies heavily on the Voting Strategy interface. We need to review the structure and see if any extensions need to be made.

**Details**
- Pair with Aditya to review current structure (pair to lead exploration)
- Create recommendation for any changes
- Pair with Nate on follow-on stories

**Related discussions**
- [Should quadratic votes pass through Round Contract?](https://github.com/gitcoinco/grants-round/discussions/338)
- [What parameters should pass between Round Contract + Voting Contract?](https://github.com/gitcoinco/grants-round/discussions/339)

**Comment by thelostone-mc** [comment]
@vacekj Had sometime to think over this and there are a few changes which we should explore making.
The understanding from #328 is that we would end up having an individual contract per round.

This means we would need to keep a factory pattern (similar to round / program) for each votingStrategy 

```
contracts/
  votingStrategy/
    BulkTransferStrategy/
      BulkTransferStrategyFactory.sol
      BulkTransferImplemenationStrategy.sol
```

The `BulkTransferStrategyFactory.sol` would essentially we responsible for creating an instance of `BulkTransferImplemenationStrategy` and emit events while doing so thus ensuring the subgraph be able to index the votes.  
What do you reckon ?

**Comment by vacekj** [comment]
sounds reasonable, let's do it
