### ISSUE TITLE
spike: redeploy fresh on after OVM 2.0

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#330]
**timebox to half a day**

### Description

With the release of OVM 2.0 we might have to 

- deploy the contracts
- redeploy the subgraphs

This is a spike to understand what should be done and when for which we'd have to reach out to the optimism and subgrpah team

https://discord.com/channels/438038660412342282/438070074700464128/897914187085389854

Optimism is upgrading to OVM 2.0. Once that happens, all historical transactions and logs will be inaccessible from the new chain, and the new chain will start from Block #0. The old chain data will not be accessible except under extreme circumstances.

OVM 2.0 will be released October 14th on the Kovan test network, and October 28th into the production Optimistic Ethereum network.

**What does that mean for subgraphs?**

Hosted service subgraphs will no longer be able to access transactions or logs from before the upgrade, and will be rewound. If your subgraph data sources use a start block, they may need to be redeployed with the new "0" startblock. You might already be aware of this due to this tweet from the Optimism team but we wanted to make sure you heard it from us as well. 

If you have any questions, please let us know here in our Discord or reach out to Optimism directly. Thanks and I hope you have a great rest of the week.

**Comment by thelostone-mc** [comment]
Closing this out cause was already done !
