### ISSUE TITLE
Create Grant Explorer nav bar

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#349]
**User Story:**
As a voter
I want to have a nav bar
So that I know how to navigate Grant Explorer

**Acceptance Criteria**
GIVEN that I am on Grant Explorer
WHEN I look at the top of the page
THEN I see a basic nav bar 

~~GIVEN that I am on Grant Explorer
WHEN I click on the Grant Explorer name in the nav bar
THEN I am brought to the main Grant Explorer page~~

This includes adding:
- Gitcoin logo
- Grant Explorer name
- Search icon (not clickable)
- Cart icon (not clickable)

This **does not** include:
- integrating wallet solution (will be in follow-on story)

**Product & Design Links:**
- [Miro mockup](https://miro.com/app/board/uXjVPYmqufs=/?moveToWidget=3458764532902872180&cot=14)
- [Figma file](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=295%3A1832)

**Tech Details:**
- Dependent on #354 

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
@nfrgosselin where would we find the svg for the grant explorer logo

**Comment by melissa-neira** [comment]
@thelostone-mc here's the svg

![Image](https://user-images.githubusercontent.com/87520659/190437925-ce189b7d-c835-44e2-b761-c709e6dfbac2.svg)

**Comment by thelostone-mc** [comment]
Oh could we get with the logo as well ?

**Comment by melissa-neira** [comment]
@thelostone-mc here you go
![Grants Explorer](https://user-images.githubusercontent.com/87520659/191716032-39db562e-f163-4ed0-b3fd-89a54b9c3d83.svg)

**Comment by melissa-neira** [comment]
@thelostone-mc here you go! I'm not sure if this is the finalized version, but use it as a placeholder for now
![Grants Round Manager](https://user-images.githubusercontent.com/87520659/191716182-f1c2073c-d646-4a09-a32b-171268f6e169.svg)

**Comment by vacekj** [comment]
Is [this](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=521%3A3902) the correct, updated design? Just to confirm, cuz what @melissa-neira posted above is quite different, but the currently implemented design seems to already be close to the one in Figma.

**Comment by melissa-neira** [comment]
@vacekj I've been updating the designs in Figma post-Nate's story writing. The nav bar that you linked to is the newest iteration of the design that I've been working on, with the new logo and icons

**Comment by lthrift** [comment]
@melissa-neira I see 3 versions of the Nav bar in the linked Figma file. Which one was supposed to be implemented? 

@vacekj when I click the Grant Explorer logo (AC #2), I get a 404. Going to send this one back to In Progress.

**Comment by vacekj** [comment]
@lthrift the main page is currently not implemented, but the redirect happens correctly.

**Comment by melissa-neira** [comment]
@lthrift the first version you see is for the empty state/preround screens and also when a wallet is disconnected (bear in mind that stories for this screen have not yet been written). The second version you see is during an active round when a user's wallet is connected. The third version can be disregarded as that is from an older version of the screens. I left it there just in case, but happy to remove it if it makes it less confusing.

**Comment by lthrift** [comment]
@melissa-neira ah, i see. we probably need to update the process a bit to specifically link the components that should be used by each story. In this case, the third version is the one that was implemented. 

---
@vacekj can we update this to use the second version that Melissa calls out in her comment above? It is the header version that has a hand lifting a heart rather than a shopping cart. 

Re: the redirect, the "main page" as I understand is the first page of the app which is currently just a placeholder with the round name and program ID. However, I'm going to pull this AC out of this story and start a thread separate thread on this as there are several details that are not fleshed out fully. Can you remove the redirect behavior for now, please?

**Comment by vacekj** [comment]
@lthrift 
- removed redirect
- fixed navbar to reflect the second, correct version from figma

**Comment by melissa-neira** [comment]
@vacekj hey the nav bar looks good to me but the spacing between the search bar and the give icon should be 24px and I think it's 16px in the preview but I might be wrong 😅

**Comment by thelostone-mc** [comment]
Oh we missed that. updating it @melissa-neira ^_^

**Comment by nfrgosselin** [comment]
LGTM with the updated AC — thanks for documenting all the discussion here everyone
