### ISSUE TITLE
Integrate wagmi + rainbowkit with Grant Explorer

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#350]
**User Story:**
As a voter
I want to have a solution for connecting my web3 wallet
So that I can interact with the page

**Acceptance Criteria**
GIVEN that I am on Grant Explorer and do not have my wallet connected
WHEN I look at the nav
THEN I see an option to connect my wallet

GIVEN that I am on Grant Explorer and do not have my wallet connected
WHEN I click the Connect My Wallet button
THEN I am able to use the wagmi/rainbow wallet connection flow

GIVEN that I am on Grant Explorer
WHEN my wallet is connected
THEN I see the wagmi/rainbow connect wallet options (match Round Manager)

**Product & Design Links:**
- [Miro mockup](https://miro.com/app/board/uXjVPYmqufs=/?moveToWidget=3458764532907936914&cot=14)
- [Figma file](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=295%3A1832)

**Tech Details:**
- Dependent on #349 

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
@nfrgosselin It looks like the rainbowkit piece is already wired in ! 
Would you be able to test and validate taht ?

**Comment by nfrgosselin** [comment]
LGTM
