### ISSUE TITLE
Create CI/CD pipeline for Grant Explorer

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#354]
### Description

- Create fleek env for round explorer (branch : main) staging & release (branch: release)
- Setup github hook to update staging env when PR is merged into main
- Setup github hook to update release env when PR is merged into release
- Enable dedicated PR env when a PR is raised against main

**Comment by thelostone-mc** [comment]
Added a few basic changes in 7d4e22e841df788c97a3c4cebae0135a71025635 to set the foundation for this ticket to be picked up

**Comment by thelostone-mc** [comment]
@nfrgosselin let's bring this up on standup :P it has a couple of things which we'd need to change

**Comment by nfrgosselin** [comment]
LGTM
