### ISSUE TITLE
Add Program contract address to Round metadata

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#358]
**User Story:**
As a Grant Hub engineer
I want to be able to access the Program contract address in the Round metadata
So that I can fetch it without having to query the subgraph

**Acceptance Criteria**
- Program contract address is available in Round metadata

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
This has been verified by the hub team: https://discord.com/channels/562828676480237578/1017772055858528307/1022435079865245726
