### ISSUE TITLE
Rename BulkVote -> QuadraticFundingVote

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#359]
**User Story:**

- Rename BulkVote contract to `QuadraticFundingVote`
- Get test coverage of BulkVote to 100%

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by t-proctor** [comment]
@nfrgosselin can you assign this to me? Will start work in next 24 hours

**Comment by t-proctor** [comment]
Also, if the current contract is called `BulkVotingStrategy`, did you want everything to be renamed `QuadraticFundingVotingStrategy` or just `QuadratingFundingVote`?

**Comment by thelostone-mc** [comment]
@t-proctor it should be `QuadraticFundingVotingStrategy` ! 
This is up for grabs if you're up for it

**Comment by t-proctor** [comment]
> @t-proctor it should be `QuadraticFundingVotingStrategy` ! This is up for grabs if you're up for it

Thanks yeah will work on it
