### ISSUE TITLE
Create script to cast votes 

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#363]
**User Story:**

The goal here is to create helper deploys scripts where given a QF round with a created by a program.
You should be able to invoke the vote function and cast 2 votes against the round for 2 diff projects

**Acceptance Criteria**
- Vote events are emitted on voting contract on Goerli

Note: Ensure documentation is updated in the deploy process to explain how this works

**Comment by shavinac** [comment]
Seems to be resolved by https://github.com/gitcoinco/grants-round/pull/466 ? 
@thelostone-mc is there further work to do on this story?

**Comment by thelostone-mc** [comment]
You're right ! That's already closed via #466
