### ISSUE TITLE
Add input types to application metadata

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#376]
**User Story:**
As a Grant Hub engineer
I want to know what type of input is expected by application questions
So that I can build validation into the application form

**Acceptance Criteria**
- for round application questions, add an `inputType` for each question in the metadata

Starting input types: email, URL, address, number, text

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
Awaiting further clarification on standup, releavant discussion: https://discord.com/channels/562828676480237578/962026258273804398/1022635112053088306
