### ISSUE TITLE
Check for no votes

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#380]
**User Story:**
As a QF smart contract
I want to send my votes to an offchain calculation service
So that my funding allocation can be allocated cheaply

**Acceptance Criteria**
GIVEN that I have sent 0 votes to the calculation app
WHEN I ask for the current results
THEN the app tells me that no votes have been received

**Product & Design Links:**

**Tech Details:**
- [Flow in Miro](https://miro.com/app/board/uXjVPY3Csls=/?moveToWidget=3458764532978275196&cot=14)
- Assuming that this is where base skeleton of the app is created

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by shavinac** [comment]
Suggested AWS Stack:
- AWS Lambda for handling requests (asking for current results)
- AWS API Gateway for accepting incoming HTTP requests (e.g. `GET qf.gitcoin.co/results`) and directing them to the Lambda for handling/response

On Passport we used Pulumi to manage deploying / updating AWS resources, see https://github.com/gitcoinco/passport/tree/main/infra for Pulumi configs, [iam-cd-review.yml](https://github.com/gitcoinco/passport/blob/main/.github/workflows/iam-cd-review.yml) for example of CI/CD of those AWS resources
