### ISSUE TITLE
Calculate single vote

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#381]
**User Story:**
As a QF smart contract
I want to send my votes to an offchain calculation service
So that my funding allocation can be allocated cheaply

**Acceptance Criteria**
GIVEN that I have data for one vote
WHEN I send that vote to the calculation app
THEN I receive the results based on that one vote

**Product & Design Links:**
- [Flow in Miro](https://miro.com/app/board/uXjVPY3Csls=/?moveToWidget=3458764532978275196&cot=14)
- Don't worry about persisting results at this point
- Assuming that this is building the calculation component
- This does not include pulling data from the subgraph

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Code reference: https://github.com/dcgtc/dgrants/blob/main/dcurve/src/internal/calc/linear.ts

**Comment by thelostone-mc** [comment]
We would need build this out first

![Image](https://user-images.githubusercontent.com/5358146/203556172-772d882b-f56b-4052-87ee-f2abf2a2bd27.png)
