### ISSUE TITLE
Remove socials from application metadata

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#387]
**User Story:**
As a project owner
I don't want to see socials in the application form
So that I don't have to double-enter my information

**Acceptance Criteria**
- Remove Twitter, Github, and Github Org questions from Application metadata (since they will be gathered in project data)

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by shavinac** [comment]
blocking - see update in discord thread ["Twitter & Github on Round Manager application details page is incorrect"](https://discord.com/channels/562828676480237578/1021913968941469817/1022167301786697778)

> When I apply to round adding a twitter handle BUT not verifying it -> twitter handle is not sent in the application
> Also Github username info is not sent in the application

**Comment by shavinac** [comment]
would RM need to load the project's metadata (from the project registry) to retrieve/verify socials, or can/should RM trust application info is truthful enough?

for convenience:
* [ProjectRegistry (goerli)](https://goerli.etherscan.io/address/0x832c5391dc7931312CbdBc1046669c9c3A4A28d5#readProxyContract#F3)
* `projects(32)` returns  `{id: 32, metadata: {1, bafkreibebwnorjiolmvfy6tdvozvz4tf4tvoh6r3twhvs2gsfcfbrrpdjm`
* my project (id = 32) [IPFS metadata](https://gitcoin.mypinata.cloud/ipfs/bafkreibebwnorjiolmvfy6tdvozvz4tf4tvoh6r3twhvs2gsfcfbrrpdjm) -- does have socials included
* here's that project's application to a round ([IPFS](https://gitcoin.mypinata.cloud/ipfs/bafkreigxpgapbgwqgc3niphgegl7mmbbhovgfnxn3hckjgbcw4u3xn6kpa))
* Question: will socials (Twitter, GitHub username, GitHub org) be included directly in the application? if so, does RM also need to verify socials claimed in application match with socials in project registry?

**Comment by lthrift** [comment]
looks good - accepting and moving to done
