### ISSUE TITLE
Round page breaking due to different received application

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#394]
**Overview**
The round page is breaking because one of the received applications is using a new schema format with a signature. You can see the issue [here](https://share.vidyard.com/watch/K1K3Q6vyM7FkYqLxzPv81H?).

This is likely due to the face that grant hub had notified round manager team already about the change, but round manager has not yet implemented the changes to handle the new format (see https://github.com/gitcoinco/grants-round/issues/388)

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/
2. Click on 'My Test'
3. Click on 'Random Round'

**Observed  behavior**
Page goes blank

**Expected behavior**
Page should load

**Comment by shavinac** [comment]
another round that shows the same error when attempting to load the round detail page in RM: https://granthub.gitcoin.co/#/chains/5/rounds/0xb822af46bb8f9f1ee49443e836e554db729dc810

round project id: 0x9af7df69878c6f3b0fd23194cfeac98833a64751582bdd9cdaeddad2294e8280-0xb822af46bb8f9f1ee49443e836e554db729dc810 ([IPFS metadata here](https://gitcoin.mypinata.cloud/ipfs/bafkreignf5ygxdubjyxybm664zuynq6msvmbz5bv4x5pdinpupvrqjl4jq))

**Comment by lthrift** [comment]
Could someone make me an operators of the rounds with this issue? I'm not able to recreate the problem with a new round. 

Here's the address I'm using for testing: 0x07FdE37f0e622DEEC96D17120f99C929D7fB1785

**Comment by lthrift** [comment]
@shavinac or @thelostone-mc bumping my comment above so I can test this one

**Comment by lthrift** [comment]
confirmed this using Shavina's recreation steps. thank you @shavinac !
