### ISSUE TITLE
Update Copy to Clipboard

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#396]
**User Story:**
As a round operator
I want feedback when I copy the application link to clipboard
So that I know that the copy was successful

**Acceptance Criteria**
GIVEN that I am on the Round Details page
WHEN I look at the "copy to clipboard" button
THEN I see the unselected state (lighter purple + "Copy to Clipboard" text)

GIVEN that I am on the Round Details page
WHEN I click on the "copy to clipboard" button
THEN the button changes to the selected state (darker purple + "Copied to Clipboard" text)
AND reverts to unselected state after a few seconds

**Product & Design Links:**
- [Unselected state](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=1650%3A9835)
- [Selected state](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=1655%3A9977)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by shavinac** [comment]
Moving back to in-progress for some UI tweaks -- the "Copy to clipboard" / "Copied to clipboard" button animation should be the same width, so the animation looks smoother. [See Melissa's Discord message](https://discord.com/channels/562828676480237578/1016703008828051507/1022842234284019812) for the mockups

**Comment by lthrift** [comment]
this looks good to me. @melissa-neira can you review for final design checks? Just comment here if it's good and change the status to "done".

**Comment by melissa-neira** [comment]
@lthrift where can I see this? I'm checking https://bafybeihv2mpnsqvzmvrtdztgxef7yt7velp7inqx6hd7wsg3gj7ge4u5ze.on.fleek.co/
and I don't see the change reflected here. Is there an updated link to check this on?

**Comment by melissa-neira** [comment]
Ok, found the current link. The button looks good to me! I however don't have the ability to change the status to done for some reason @lthrift

**Comment by shavinac** [comment]
Moved to "Done" (i needed to manually change the status in the dropdown since we no longer have a "Done" column)


![Image](https://user-images.githubusercontent.com/62616399/192815212-36b9970b-510f-4d64-85b1-2cf35e13955c.png)

**Comment by melissa-neira** [comment]
Thanks so much @shavinac! I don't have the same editing options as you though - is there a way to fix this?
<img width="328" alt="Screen Shot 2022-09-28 at 17 09 15" src="https://user-images.githubusercontent.com/87520659/192816196-9c19decc-906b-4c97-8aa3-bbfa6c567b24.png">

**Comment by shavinac** [comment]
@melissa-neira hmm, looks like you aren't one of the Grant Round project members 🤔 I'll try to add you
If you're a member of the `gitcoinco` GitHub organization, I think that should automatically give you access to the project as well
