### ISSUE TITLE
spike: can applications be marked invalid in subgraph

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#397]
**Overview**
For potential fraudulent applications, we want to be able to record them in the subgraph has invalid for future data analyses. Details here #388 

**Details**
Say more

**Comment by thelostone-mc** [comment]
Moving this to blocked until IPFS by subgraph is more deterministic

**Comment by nfrgosselin** [comment]
Closing as irrelevant for now
