### ISSUE TITLE
Update processing modal on Program deploy

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#398]
**User Story:**
As a round operator
I want to see a step in the processing flow for subgraph indexing
So that I'm not redirected before the data is ready

**Acceptance Criteria**
GIVEN that I have initiated any wallet transaction
WHEN I see the processing modal
THEN I see a new "indexing" state after "deploying" that is live when the subgraph is indexing the data

GIVEN that I have initiated any wallet transaction and am looking at the new processing modal
WHEN the subgraph is done indexing the data
THEN I am redirected to the appropriate page

GIVEN that I have initiated a transaction to deploy a program
WHEN I see the processing modal
THEN I see the new processing modal
AND am redirected to My Programs once all steps complete

**Product & Design Links:**
- https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=1563%3A8877

**Tech Details:**
- WIP branch -- [398--update-processing-modal-on-program-deploy](https://github.com/gitcoinco/grants-round/compare/398--update-processing-modal-on-program-deploy)

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
A smart way we could go about this is by getting 
the block number of the signed txn of the frontend
and comparing it with our subgraph to check if the latest block has been indexed 

The query would look like this : 
```
{
  _meta {
    block {
      number,
      hash
    }
  }
}
```

**Comment by lthrift** [comment]
There was a conversation in Discord here https://discord.com/channels/562828676480237578/1024090719872368780/1024090723101978705 discussing what to do if indexing failed and it was agreed to move that to a separate story.

However, it looks like the modal update was only implemented for creating a program. I don't see it updated when creating a round and there is no processing modal at all when approving an application. 

https://www.loom.com/share/6f7c6d95be3543a1b2489424ed89e39f

**Comment by thelostone-mc** [comment]
@lthrift so those are tracked in other tickets in our backlog.
This was focussed only on creating a program

**Comment by lthrift** [comment]
@thelostone-mc the AC says "GIVEN that I have initiated **any wallet transaction** and am looking at the new processing modal"

Where are the other stories - are we out of sync on these somewhere?

**Comment by shavinac** [comment]
Originally this story was to replace all of the processing modals throughout the app, but we split up the stories last IPM to target each usage separately:
https://github.com/gitcoinco/grants-round/issues/398 (this ticket)
https://github.com/gitcoinco/grants-round/issues/399
https://github.com/gitcoinco/grants-round/issues/400
https://github.com/gitcoinco/grants-round/issues/401

**Comment by lthrift** [comment]
oh geez... i see now the title was updated and the AC was not. sorry ya'll.
