### ISSUE TITLE
Update processing modal on bulk approve/reject

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#400]
**User Story:**
As a round operator
I want to see the stepped progress modal when I bulk approve/reject grants
So that I understand how the process works

**Acceptance Criteria**
GIVEN that I have **initiated** a transaction to bulk approve/reject grants
WHEN I click the confirm button on the confirmation modal
THEN I see the stepped processing modal
AND am redirected to the application tab that I was previously on once all steps complete

GIVEN that I have **confirmed** a transaction to bulk approve/reject grants
WHEN I see the stepped processing modal
THEN I see the "application approval" steps in the modal (see below)

**Product & Design Links:**
"Application Approval" steps:
1. Storing - The metadata is being saved to a safe place
2. Updating - Connecting to the <chain name> blockchain
3. Indexing - The subgraph is indexing the data
4. Redirecting - Just another moment while we finish things up

confirmation modal:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/15041635/193641528-a0851f38-0126-4c9c-922d-8756b3f75cd0.png">

**Tech Details:**
- depends on #395 
- see `packages/round-manager/src/features/api/subgraph.ts` for basic subgraph polling function for current block number

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
@shavinac — FYI that I updated the AC per our discussion in Discord [here](https://discord.com/channels/562828676480237578/1025534943083905136/1026519007274225755)

the tl;dr is that we should show the stepped processing modal after the user clicks the confirm button

**Comment by nfrgosselin** [comment]
LGTM!

**Comment by melissa-neira** [comment]
LGTM +1! 🔥
