### ISSUE TITLE
Update processing modal on Application Details page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#401]
**User Story:**
As a round operator
I want to see the stepped processing modal on the individual application approval flow
So that I know how the process is progressing

GIVEN that I have initiated a transaction to approve an individual grant on the Application Detail page
WHEN I click the confirm button on the confirmation modal
THEN I see the stepped processing modal
AND am redirected to the application tab that I was previously on once all steps complete

GIVEN that I have confirmed a transaction to bulk approve/reject grants
WHEN I see the stepped processing modal
THEN I see the "application approval" steps in the modal (see below)

**Product & Design Links:**
"Application Approval" steps:
Storing - The metadata is being saved to a safe place
Updating - Connecting to the blockchain
Indexing - The subgraph is indexing the data
Redirecting - Just another moment while we finish things up

confirmation modal:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/15041635/193642060-5662af06-e4f1-4a0f-9ac1-e0465078181e.png">

**Tech Details:**
- depends on #395 
- see `packages/round-manager/src/features/api/subgraph.ts` for basic subgraph polling function for current block number

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by shavinac** [comment]
Currently the single application approve/reject modal does not show multiple "steps" (see below screenshot). it is using a different modal from "Create Program" / "Create Round"



![Image](https://user-images.githubusercontent.com/62616399/193363452-1962b60d-692c-432d-bad4-5faf40a71e55.png)


With this in mind:
- should single approve/reject be updated to use the same progress modal that "Create Program" / "Create Round" have?
- if not, how should the "indexing in progress" status be displayed / communicated with the current modal

**Comment by thelostone-mc** [comment]
> should single approve/reject be updated to use the same progress modal that "Create Program" / "Create Round" have?

I would lean towards this to keep it consistent but defer to @nfrgosselin on final say here
