### ISSUE TITLE
chore: add commit linting and commit-builder tools

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#402]
based on discussion https://github.com/gitcoinco/grants-round/discussions/322

`@commitlint/config-conventional` default rules should work for us 
https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional

Commit builder tools
* https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/prompt-cli -- commitlint's CLI prompt tool
* https://github.com/commitizen-tools/commitizen -- independent tool that also offers a prompting CLI
* plugins for VSCode / JetBrains ?

**Comment by lthrift** [comment]
@thelostone-mc i'm not sure how to accept this one. can this one be dev accepted?
