### ISSUE TITLE
Create PayoutContract skeleton

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#404]
**User Story:**

Refer here for backstory: #364 

The goal here is to create an interface for PayoutStrategy which will be then implemented by MerklePayoutStrategy (similar to the voting interface / abstract)

1. Create IPayoutStrategy.sol with  (Use IVotingStrategy for reference)
   - variable : `roundAddress`
   - function: `init`
   - function: `updateDistribution` to accept encoded info 
   - modifier: `isRoundContract`

2. Create MerklePayoutStrategy.sol which uses the IPayoutStrategy 
  - implement `updateDistribution` to decode 

```
bytes32 resultsMerkleHash //  variable to store the merkle root of the results
MetaPtr votingMetaPtr // the finalized votes dataset 
``` 

Once this is done ! 

Also write up a script to deploy this to test if this data can be saved / retrieved

**Comment by melissa-neira** [comment]
defer to engineering 👩‍🔬

**Comment by nfrgosselin** [comment]
Defer to engineering

**Comment by Jayjay1488** [comment]
Hey I am trying to figure out how to do this if you can help please email me at jamiechimileski19@gmail.com or jaimechimileski@gmail.com thank you
