### ISSUE TITLE
Script to deploy payout contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#406]
**User Story:**
As a
I want to
So that

**Acceptance Criteria**
- payoutcontract is deployed on Goerli via Script

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Clubbing this with #404 as it's not possible to verify the output of payout contract otherwise 
@nfrgosselin
