### ISSUE TITLE
Fix eslint warnings

### ISSUE THREAD

**Issue by vacekj** [gitcoinco/grants-round#411]
# User Story:
As a developer
I want to disable ignoring of eslint warnings and fix the errors
So that our code is clean and functional

# Acceptance Criteria
- the following rule overrides are removed in `.eslintrc.js` root configuration:
```
  "@typescript-eslint/no-non-null-assertion": "off",
  "@typescript-eslint/no-empty-function": "off",
```
- the command `CI=true yarn lint:fix` passes without warnings or errors
- specific overrides for certain file patterns (e.g. turn off `no-empty-function`, `no-non-null-assertion` rules for all test files) should be used if reasonable

# Notes
- empty functions that violate the `@typescript-eslint/no-empty-function` rule should have comments inserted in them explaining why they are empty / why they are necessary

**Comment by melissa-neira** [comment]
defer to engineering 🕺

**Comment by nfrgosselin** [comment]
Defer to engineering!
