### ISSUE TITLE
Form validation on Application Start Date

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-round#414]
**Overview**
When creating a round does the app start date have to be after today/current date? Looks like there is a revert in the contract 🤔 https://github.com/gitcoinco/grants-round/blob/2b596828c0862c71f85eb98e8a2ebfbd287a6068/packages/contracts/contracts/round/RoundImplementation.sol#L204

**Steps To Reproduce**
1. Go to https://round-manager.gitcoin.co/#/round/create?programId=PROGRAM_ID
<img width="709" alt="Screen Shot 2022-09-20 at 9 29 21 AM" src="https://user-images.githubusercontent.com/9419140/191274018-a22bbac4-d30e-46f1-87e5-87b87e33ed40.png">
<img width="713" alt="Screen Shot 2022-09-20 at 9 48 55 AM" src="https://user-images.githubusercontent.com/9419140/191275390-c884598c-9528-476f-ba0c-1fb0e2185fc9.png">

**Observed  behavior**

- [ ] noticed nothing stopping me from moving forward if I enter todays date.
- [ ] noticed that the end date(s) were not required, not sure if this was expected behavior.

**Expected behavior**
To not be able to click 'Next' until all required values are entered.

**Comment by DanieleSalatti** [comment]
+1

Also there's no indication of what the error is unless you check the console.

**Comment by shavinac** [comment]
it's very easy to miss, but the create round form lets you set both the date and time for the start/end inputs. (see attached screenshots below)

the datetime selector in the form will use your computer's local timezone, so please try creating a round making sure to set a future time.

for the application / round end dates, we have previously discussed allowing round operators to create an "indefinite" round with no end date, but i will defer to @nfrgosselin (cc @lthrift ) if we should make all dates required for now.

![Image](https://user-images.githubusercontent.com/62616399/193151596-4d00bcd7-c5f2-419b-9e5f-68838bbbcf85.png)
![Image](https://user-images.githubusercontent.com/62616399/193151597-3594e3e8-019a-42e0-8a92-588d6d1df9b1.png)

**Comment by nfrgosselin** [comment]
Thanks for dropping this @codenamejason! This isn't a bug (just a quirk of the UI) — I've created a separate story here #450 and will close this out
