### ISSUE TITLE
bug: ensure both env rm & ge env are shown when a PR is raised

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#422]
Follow discussion here: https://discord.com/channels/837010835423494144/902989327267659836/1022460524765651004

**Comment by thelostone-mc** [comment]
Fleek moved their discord channel.
They've ack it's a bug and have offered to push a hotfix 

Waiting on that ATM

**Comment by shavinac** [comment]
looks like fleek fixed this 🎉 

![screenshot of multiple fleek sites appearing in PR CI checks](https://user-images.githubusercontent.com/62616399/194164409-8557fb7f-14ba-4721-983c-46dc3ef32e7d.png)

**Comment by thelostone-mc** [comment]
I think it's almost there:
The preview link still appears as 1 which is disappointing and I've raised that up with the fleek team


![Image](https://user-images.githubusercontent.com/5358146/194212964-184c8fbb-c47e-4ccb-a7df-995e13f0ccf7.png)

**Comment by thelostone-mc** [comment]
> The problem is we are using also Commit Status API (fleek/build) and that does not support having multiple async statuses per commit. 
But besides that we are using classic Check Run APIs which you can see as gegitcoin and rmgitcoin and if you click on these runs you should see preview URL on that page.

**Comment by nfrgosselin** [comment]
deferring to eng approval
