### ISSUE TITLE
read project socials (twitter, github, github org) from project metadata in application instead of from questions

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/grants-round#427]
Related to https://github.com/gitcoinco/grants-round/issues/387

Since Twitter/GitHub/GitHub Organization info will be removed from application questions, the username/handle info will instead be included as part of the project metadata embedded in the grant application. Verifiable credentials will remain in the application as they were before.

RM will need to update its verification code for the verifiable credentials -- there is a check that the plaintext username/handle claimed in the VC matches the project's claimed username/handle. Currently RM is doing this check against the application questions/answers, but now it should check against the project metadata directly.

See https://gitcoin.mypinata.cloud/ipfs/bafkreidezr6jj2qcg6ijhoveilbq72qvh464773q4w23unit2onyzmidvy for an example application with socials in the `application.project` object

See discord thread for more context - https://discord.com/channels/562828676480237578/1021913968941469817

**Comment by nfrgosselin** [comment]
LGTM!
