### ISSUE TITLE
update application question labels to human-friendly copy

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/grants-round#430]
Update the application schema generated during round creation to have human-friendly labels
Update round application form labels to stay consistent with the labels in the schema

* `Email` -> `Email Address`
* `Funding Source` -> `Funding Sources`
* `Profit2022` -> `2022 Profit`
* etc

see discord thread - https://discord.com/channels/562828676480237578/1022908453389344789

**Comment by nfrgosselin** [comment]
LGTM
