### ISSUE TITLE
Cleaner date picker UX

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#450]
**User Story:**
As a round operator
I want the UI to provide clearer feedback around valid round dates
So that I don't have unnecessary / unclear errors

**Acceptance Criteria**
GIVEN that I am on the first step of the round creation page and have clicked on a date field
WHEN the date picker opens
THEN past dates are grayed out
AND I cannot select past dates

GIVEN that I am on the first step of the round creation page
WHEN I select today's date
THEN the time defaults to the top of the next hour (e.g. if it is 10:45, then the time will set at 11:00)

GIVEN that I am on the first step of the round creation page and have entered a date+time prior to the current time
WHEN I click the Next button
THEN I see a validation error under the field with the incorrect date that says "You must enter a date and time in the future."

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
Also noticed that the `type` of the date inputs is not `date`, which means some extensions might not work well. Ideally we should at least make the aria attribute date, if the `type` can't be made `date` due to technical limitations.

**Comment by dschinkel** [comment]
Note: We've covered the third scenario (show validation error) by ensuring a user can't select a date/time prior to current time.  So no need for an error message.  @dschinkel @thelostone-mc reviewed this with @nfrgosselin as well.

**Comment by dschinkel** [comment]
@vacekj we addressed the type on input by setting `type="date"` and that seemed to work fine on the `DateTime` component
