### ISSUE TITLE
Revise default application configuration page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#451]
**User Story:**
As a round operator
I want to remove the edit button from the application configuration page
So that I don't try to use an incomplete feature

**Acceptance Criteria**
GIVEN that I am on the Review Information step of the round creation flow
WHEN I look at the page
THEN I don't see the edit button above the application questions

GIVEN that I am on the Review Information step of the round creation flow
WHEN I look at the Application Information section
THEN I see (4) default questions:
- Payout Wallet Address
- Email Address
- Funding Sources
- Team Size

GIVEN that I am on the Review Information step of the round creation flow
WHEN I look at the source code
THEN I see a data structure skeleton that supports the design

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=1916%3A14834)
![image](https://user-images.githubusercontent.com/15041635/193611791-f505ed28-fd95-4b4e-a294-0cb87bb32d4e.png)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Would tweak this to hide the button cause in V2 we'd have to re-use this functionality  (which is paritally built out)
