### ISSUE TITLE
Round Details not loading

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#454]
**Overview**
The round details page isn't loading on prod (see screen capture)

**Screenshots**
https://share.vidyard.com/watch/qx3TYWQnroEt28JFR1b1sq?

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by shavinac** [comment]
This should be resolved when https://github.com/gitcoinco/grants-round/pull/416 is deployed to production
