### ISSUE TITLE
Add round details to application view page

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#474]
**User Story:**
As a round operator
I want to configure what the application page will say on Grant Explorer
So that I can tell potential grantees exactly how to get involved in my round

**Acceptance Criteria**
GIVEN that I am on Grant Explorer for a specific round
WHEN it is on or after the round start date
THEN I see the explorer view of the landing page

GIVEN that I am on Grant Explorer for a specific round
WHEN it is before the round start date
THEN I see the application view page

GIVEN that I am on the application view page for a specific round
WHEN I look at the page
THEN I see the round eligibility details in the left column

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1055%3A27117)

**Tech Details:**
* [Example Round Metadata](https://gitcoin.mypinata.cloud/ipfs/bafkreifco4ffsnqsvvu2zu4gkavexqnrmnj2fhrksm2anlg6wzqb6h3btm) with eligibility, based on schema updates in PR https://github.com/gitcoinco/grants-round/pull/538

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by shavinac** [comment]
Here's an [Example Round Metadata](https://gitcoin.mypinata.cloud/ipfs/bafkreifco4ffsnqsvvu2zu4gkavexqnrmnj2fhrksm2anlg6wzqb6h3btm) IPFS document with eligibility info, based on schema updates in PR https://github.com/gitcoinco/grants-round/pull/538

You can also create your own round with eligibility requirements using the PR preview
