### ISSUE TITLE
Remove from final donation

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#488]
**User Story:**
As a donor
I want to be able to remove projects from my final donation
So that I can narrow down my final choices

**Acceptance Criteria**
GIVEN that I have projects on my final ballot
WHEN I click the back arrow icon
THEN the project is removed from my final donation
AND the project is added back to the shortlist

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A63811)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
@thelostone-mc just to confirm, this is already fixed by #645 right?

**Comment by thelostone-mc** [comment]
Yup that is right! We just needed to wire it to the UI
