### ISSUE TITLE
Copy amount to other projects

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#490]
**User Story:**
As a donor
I want to be able to apply an amount to all projects
So that I can easily make donation decisions

**Acceptance Criteria**
GIVEN that I am on the Donation Builder and have projects on my final donation
WHEN I look at the top of the final donation
THEN I see the "Amount / Currency" numeric entry field
AND a "Apply to All" button

GIVEN that I have entered an amount in the "Amount / Currency" numeric entry field
WHEN I click "Apply to All"
THEN that amount is copied to all the projects in my final donation
AND the "Your Contribution" summary amount updates

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1055%3A27643)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
@bhargavaparoksham make sure you rebase off the  637-update-token-units-based-on-drop-down cause I've done some test refactoring there and it might lead to conflicts
