### ISSUE TITLE
spike: explore where to store strategy ID

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#495]
**timebox to half a day**

**Overview**
The Grant Explorer will need to change some UI elements depending on which voting strategy is being used. For example, the ballot builder will have to know to use votes if it's a QV round and specific tokens if it's a QF round. We need to figure out how to signal to the UI which strategy is in use so that those UI elements can update. 

**Details**
The scope of this ticket is to: 
- explore whether the strategy ID needs to be stored on the contract or if it can be set via the subgraph
- document findings
- Pair with Aditya and Nate on follow on stories

**Comment by thelostone-mc** [comment]
Thinking out loud -> Maybe we just add a name variable in the strategy which is hardcoded to the strategy type

**Comment by thelostone-mc** [comment]
From what I've seen and implemented on https://github.com/gitcoinco/grants-round/pull/532. I would say we can get away with relying on the subgraph for this.
