### ISSUE TITLE
feat: update QFVotingStrategy to allow native token transfer

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#496]
### Description

The goal here is to update the QFVotingStrategyImplementation contract to support native tokens transfer and not just ERC20.
All we would have to do here in the vote function :
- change the token type to an address
- if address == 0x  -> do a regular transfer
- else do a ERC20 transfer

Ensure tests are added to account for native token transfer  as a part of this ticket

**Comment by nfrgosselin** [comment]
Defer to eng acceptance on this 👨‍🎨
