### ISSUE TITLE
Add link to GE in RM

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#505]
**User Story:**
As a round operator
I want to have a link to my round's explorer in Round Manager
So that I can easily access my round

**Acceptance Criteria**
GIVEN that I am on the Round Details page 
WHEN I click on the "View on Grants Explorer" button
THEN my round's Grant Explorer opens in a new tab

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=1916%3A15726)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by dschinkel** [comment]
When running the apps locally add this to your round manager .env

REACT_APP_GRANT_EXPLORER=http://localhost:3001

Then run RM on port 3000 and GE on port 3001 for this link to work

@thelostone-mc we also added that key to fleet, but will need to have you add it to the staging server as we don't have access to be able to add that

**Comment by melissa-neira** [comment]
@dschinkel can we go over this in standup today please? I can't get it to work 😅

**Comment by thelostone-mc** [comment]
@dschinkel I've updated both on staging and live

**Comment by nfrgosselin** [comment]
@thelostone-mc this still isn't working for me? I'm getting this screen

![image](https://user-images.githubusercontent.com/15041635/196464086-0c9826ce-ffd1-4cce-8e3e-9a3482db679d.png)

**Comment by melissa-neira** [comment]
^same here. Was about to comment but Nate beat me to it!
