### ISSUE TITLE
Initiate donation submission

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#506]
**User Story:**
As a donor
I want to submit my donations
So that my chosen grants can receive my support

**Acceptance Criteria**
GIVEN that I have projects in my final ballot and **have not** entered donation amounts for all projects
WHEN I click the "Submit Your Donation" button
THEN I see an error message below the button that says "You must enter donations for all final ballot projects"

GIVEN that I have clicked the "Submit Your Donation" button
WHEN I do not have enough funds in my wallet
THEN I see an error "You do not have enough funds for these donations"

GIVEN that I have projects in my final ballot, have entered donation amounts for all projects, and have enough funds in my wallet
WHEN I click the "Submit Your Donation" button
THEN I see the donation confirmation modal

GIVEN that I am looking at the donation confirmation modal
WHEN I click "Cancel"
THEN the modal closes
AND I am kept on the Ballot Builder page

GIVEN that I am looking at the donation confirmation modal
WHEN I click "Confirm"
THEN the modal closes (rest of workflow will be in #642)

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A56304)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
https://wagmi.sh/docs/hooks/useBalance#token-optional
