### ISSUE TITLE
Create vote event listener

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#509]
**Note: depending on timing, we could simplify to a cron job**

**User Story:**

The question here is to decide when to run the calculate function.  
There are 3 possible ways and we'll have to figure out  which works best

- run a cron job to invoke the calculate function 
- have the frontend invoke the /calculate endpoint when a user completes a contribution 
- have a smarter event listener which watches the event log on the voting contract and knows when to invoke the calculate function

**Comment by vacekj** [comment]
Notes from brainstorming with @bhargavaparoksham:
- Cron job doesn't really make sense
- frontend invoking the /calculate function opens up a DoS attack vector
- => event listener for on-chain events to run the calculation is best both in terms of security and liveness of the calculation results.

**Comment by chibie** [comment]
for DDoS attack mitigation, we could use redis for rate-limiting

reference: https://upstash.com/blog/serverless-rate-limiting

**Comment by chibie** [comment]
**Lambda service**

 Pros 
* Auto-scaling
* No long-running dedicated server
* Cheapest option
* Forces us to write optimal code

Cons
* Prone to DDoS attacks
* Has a run limit of 15 minutes


**Event listener**

Pros

* Most secure option
* No run time limit

Cons

* Needs a dedicated EC2 instance
* Requires scaling overhead
* More expensive
* We could lose events if EC2 instance is out for a minute + will require querying historical events and re-updating db

**Comment by thelostone-mc** [comment]
Follow up story: On Grant Explorer -> once votes are casted -> invoke the `/calculate` endpoint

**Comment by vacekj** [comment]
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-api.html

**Comment by vacekj** [comment]
Correct me if I'm wrong, but I think we decided on option 2: have the frontend invoke the /calculate endpoint when a user completes a contribution. Can you please confirm @thelostone-mc @chibie @hmrtn ?

**Comment by thelostone-mc** [comment]
Yup ! I am good with this

Ideally we don't even need to do it here cause this info would need to updated when the round manager wants to view the results. But yes this can be closed now
