### ISSUE TITLE
Add token units drop-down

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#512]
**User Story:**
As a donor to a QF round
I want to be able to select the token to donate to my chosen products
So that I can spend tokens that I have in my wallet

**Acceptance Criteria**
GIVEN that I am on the Donation Builder
WHEN I look above the final donation
THEN I see the heading "Amount/Currency"
AND a drop-down menu with the default token for that round listed

GIVEN that I am on the Donation Builder
WHEN I click on the currency drop-down
THEN I see a list of eligible donation tokens for that round

GIVEN that I am looking at the currency drop-down
WHEN I click on a currency
THEN the drop-down closes
AND the currency I clicked is now selected in the drop down

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1055%3A27643)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
This PR does work as expected and fulfills the AC. 

One thing to note is selecting the token from the Dropdown does not currently update the summary component and should be marked as a separate issue (update the units across both the final ballot and summary components) after merging this along with #661.
