### ISSUE TITLE
Add Matching Fund fields to Round Details (happy path)

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#513]
**User Story:**
As a round operator
I want to configure the quadratic funding settings for my round
So that the mechanism fits my needs

**Acceptance Criteria**
GIVEN that I am on the Round Details step of the round creation flow
WHEN I look at the Quadratic Funding Settings section
THEN I see text fields for "Matching Funds Available" and the matching cap percentage
AND a yes / no button for adding a matching cap to projects 

GIVEN that I am on the Round Details step
WHEN I hover over the Matching Cap yes/no tool tip
THEN I see the tooltip copy

GIVEN that I am on the Round Details step
WHEN I enter an amount in Matching Funds Available
THEN the field shows the selected token symbol as the unit (i.e. 20,000 DAI)

GIVEN that I am on the Round Details step
WHEN I enter an amount in the Matching Cap field
THEN I see a percent symbol next to the number
AND the Yes matching cap button is checked

GIVEN that I have filled out the required Quadratic Funding Settings
WHEN I deploy the round
THEN my settings are saved to IPFS

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2193%3A15103)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
> GIVEN that I am on the Round Details step
> WHEN I enter an amount in the Matching Cap field
> THEN I see a percent symbol next to the number
> AND the Yes matching cap button is checked

We actually have this reversed. The USER must select the matching cap boolean in order to enable the next field, "If so, how much?" matching percentage amount.
