### ISSUE TITLE
Create schema for Round Application form

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#55]
**Description**
As part of the Application flow, we need to give Round Operators the ability to configure the application form that they want projects to fill out. This ticket is for the engineering team to create a data schema for the MVP form questions and share with the Grant Hub team. 

**Acceptance Criteria**
Product a schema that supports:
- questions being required or optional
- the questions included in the MVP scope [here](https://www.notion.so/gitcoin/MVP-Application-Flow-Discovery-3464ae95d9734e1496b9bc699c036a37#bd1cb6321ad349b58bc4acfa16f8b74b)

**Comment by thelostone-mc** [comment]
The application form schema can be found here:
https://github.com/gitcoinco/grants-round/blob/review/packages/contracts/docs/ROUND_APPLICATION.md#application-form-schema 

This would need sign off from the review team for us to proceed

**Comment by nfrgosselin** [comment]
This looks great, thanks @thelostone-mc! I'm sharing over with the Hub team for review
