### ISSUE TITLE
task: redeploy contracts on goerli + update subgraph + update frontend

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#566]
This task contains 3 steps:

- [x] Deploy Contract on Goerli
- [x] Update round manager frontend to use new Contracts
- [x] Update grant explorer frontend to use new Contracts
- [x] Update Graph to use new Contracts

**Comment by thelostone-mc** [comment]
Moving to blocked until we get signoff from team that we can deploy the subgraph

**Comment by thelostone-mc** [comment]
Deploy => A new subgraph  ==> dummyProgramFactory

**Comment by thelostone-mc** [comment]
The Graph is deployed to 

- ENDPOINT: https://thegraph.com/explorer/subgraph/thelostone-mc/round-labs
- API : https://api.thegraph.com/subgraphs/name/thelostone-mc/round-labs

**Comment by nfrgosselin** [comment]
Accepting this

**Comment by shavinac** [comment]
Dummy smart contract with no-op `init()` method https://goerli.etherscan.io/address/0xAD8E33940a0275651FC4a3a5Ab26a53067e5E50A#code
