### ISSUE TITLE
[UI] Update New Program creation form styling

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#59]
**Overview**
Update the New Program form to MVP styling

**Details**
Change over this page (see screenshot) to use [this styling](https://www.figma.com/file/aZ3oDEvJOTWnbxn1js1SIq/Round-Manager---Wireframes?node-id=652%3A1203)
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/15041635/174190283-b4bed274-5640-426e-b4b6-3b8e437c5804.png">

**Comment by thelostone-mc** [comment]
Temporarily blocked on how to get this to work.
https://github.com/gitcoinco/grants-round/pull/107#discussion_r911340865

Adding @chibie in for a hand here 
cc @nfrgosselin
