### ISSUE TITLE
[UI] Update Program details page styling

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#60]
**Overview**
Update Program details page to MVP styling

**Details**
Change this page (see screenshot) to use [this styling](https://www.figma.com/file/aZ3oDEvJOTWnbxn1js1SIq/Round-Manager---Wireframes?node-id=714%3A746)
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/15041635/174190464-c89d687e-2e3e-487e-b060-7af2f03313ad.png">

**Comment by thelostone-mc** [comment]
Pieces like :

- image upload
- edit form
- round details 

Lack UI / needs to be built out. These have been added in the PR as dummy components but don't do anything in terms of functionality

- Edit Button -> nothing happens on click
- Default Program Banner -> cause we have no upload feature
- Round List UI -> no designs so it has been styled similar to Round
