### ISSUE TITLE
Program empty state not displaying on Fantom testnet

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#604]
**Overview**
The empty state of Round Manager doesn't display correctly on Fantom testnet. 

**Steps To Reproduce**
1. Go to https://rmgitcoin.on.fleek.co/
2. Connect to Fantom Testnet
3. See issue

**Observed  behavior**
I don't see the button to create a new program

**Expected behavior**
I should see the option to create a new program

**Screenshots**
![image](https://user-images.githubusercontent.com/15041635/199280006-f57c6316-4b4d-43d5-ac0d-2885962c49f0.png)

**Comment by hmrtn** [comment]
I cannot reproduce this on my end with Firefox. 

Can you post a screenshot of the browser console on this page? As well as details about your browser.
