### ISSUE TITLE
Project Details banner height change

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-round#611]
**User Story:**
As a user
I want consistency across all designs in the protocol
So that I have a seamless experience throughout dapps

**Acceptance Criteria**

-  Changing banner height to w: 1280px **h: 320px**

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1458%3A41922)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
https://gegitcoin.on.fleek.co/#/round/5/0xcef1772dd6764c95f14c26b25e8f012c072c5f77/0x8b6f59926411767f067c5a0bd056ef68b2323e27e0caa7cf649591609795efdf-0xcef1772dd6764c95f14c26b25e8f012c072c5f77

Looks like it's already set to the expected dimensions. Could you provide an example where it isn't ?

**Comment by nfrgosselin** [comment]
No-op
