### ISSUE TITLE
UI issues when switching chains

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#617]
**Overview**
On both staging and production for Round Manager, I'm seeing two issues when switching between chains:

1) The "empty state" isn't loading for me on chains where I don't have programs —> I should be able to see the "create new program" box when I switch to chains. You see this when I switch to the Optimism chain in the Loom.
2) Occasionally I also see programs from one chain when I switch to the other chain (later in the video)

[Loom](https://www.loom.com/share/57c347cdb7cb40319b8f0717cd1cd7ea)

**Comment by hmrtn** [comment]
This is resolved with PR #624 as the error occurs because of the subgraph deployment. 

Though it does lead to questions about how we are logging such cases...
