### ISSUE TITLE
Matching Funds Available is not getting updated in Grants Explorer

### ISSUE THREAD

**Issue by bhargavaparoksham** [gitcoinco/grants-round#633]
**Overview**
Matching Funds Available is not getting updated in Grants Explorer, round details page.

**Screenshots**
<img width="1440" alt="Screenshot 2022-11-08 at 6 10 37 PM" src="https://user-images.githubusercontent.com/22616592/200591658-2106feac-7c9d-4124-abeb-68f8b45fe440.png">

**Comment by thelostone-mc** [comment]
Example URL: https://gegitcoin.on.fleek.co/#/round/250/0x9a5506164e28848b7571176d8c7bf48938093206/

**Comment by bhargavaparoksham** [comment]
@nfrgosselin @melissa-neira Currently, the matching funds available is being added in the payout token denomination when a new round is being created. 

In the above screen should we convert it into dollars & show it  or 
show it in the native token denomination with native token symbol added next to it?

cc: @thelostone-mc

**Comment by thelostone-mc** [comment]
I would say show it in native token !

**Comment by melissa-neira** [comment]
I agree with @thelostone-mc!
