### ISSUE TITLE
UI Audit

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#636]
**Checklist (WIP)**

- [x] Images on wallet gated pages must always be aligned to the right (no right margin or padding) Example [here](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2426%3A17552)
- [x] Same for parameters apply for image on My Programs page, images must be aligned to the right. Example [here](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2426%3A17492)
(however, text and content should follow normal grid margins and padding)
- [x] Program & Round creation form font weights, size, and color: 
        - Font size should be 14 throughout
        - All font weights should be "regular", no bold fonts
        - Placeholder text & subheadings should be #757087 example:
        ![Image](https://user-images.githubusercontent.com/87520659/200052700-bc66af8c-06d2-4360-a891-28edc9b922a3.png)
        - Required tag on application form input boxes are currently missing, please update to match [design](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2426%3A15580)
- [x] Drop-down stretching outside the page width
![Image](https://user-images.githubusercontent.com/15041635/200617657-f08fb1a5-6e4e-48d1-9069-d85f30558590.png)

- [x] Uniform Gitcoin "logo" amongst all dapps. Should be "Gitcoin": in all caps, size 16, font is Futura, letter spacing is 6%, color #0E0333. Reference below and example [here](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2426%3A17552) (this occurs on the RM wallet gated page)
<img width="446" alt="Screen Shot 2022-11-10 at 14 22 21" src="https://user-images.githubusercontent.com/87520659/201187689-25a72bd5-4b1a-4c0a-8802-88a64a864596.png">

- [x] Footer alignment: footer should follow body alignment: 80px margin, right & left. Example here - [Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=2426%3A14828) (this happens across all pages in RM & GE - the icons on the right side of the footer should be aligned to the 80px margin on the right)
- [x] Donation builder box padding: Horizontal padding is 8px and vertical padding is 16px (this is the same for all boxes) See example here - [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A63811) (currently, padding in all boxes is 24px throughout) 
<img width="1920" alt="Screen Shot 2022-12-05 at 11 15 20 (2)" src="https://user-images.githubusercontent.com/87520659/205612926-274eea9a-f99d-493a-af7c-f2e08fd2ee36.png">

**Comment by thelostone-mc** [comment]
@melissa-neira blocking cause we'd need help!

Could you list out 
- where exactly the logo is to be updated
- footer -> which pages it's broken / show the difference via a screenshot btwn the two
- builder box padding -> add in screenshot / recording to explain the difference

**Comment by melissa-neira** [comment]
@thelostone-mc sure thing! just updated the story 💖

**Comment by bhargavaparoksham** [comment]
Visually the 8px padding in the ballot page, feels too small. 

<img width="1309" alt="Screenshot 2022-12-06 at 3 57 14 PM" src="https://user-images.githubusercontent.com/22616592/205886983-0e67ed4d-9092-4eeb-a34c-cd65d3eef5cc.png">

**Comment by melissa-neira** [comment]
@bhargavaparoksham yeah it definitely feels too small. let's try with 16px or 24px - I'll defer this to you guys

**Comment by bhargavaparoksham** [comment]
@melissa-neira updated the padding to 16px. The pr is ready for review now.

**Comment by nfrgosselin** [comment]
@bhargavaparoksham can you attach the PR to this story?

**Comment by bhargavaparoksham** [comment]
Its already linked. Here's the pr: https://github.com/gitcoinco/grants-round/pull/739
