### ISSUE TITLE
Connect wallet modal

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#641]
Depends on #506 

**User Story:**
As a donor
I want to submit my donations
So that my chosen grants can receive my support

**Acceptance Criteria**
GIVEN that I have filled out all required fields on the donation page AND I don't have a wallet connected
WHEN I click "submit your donation"
THEN I see the connect wallet modal

GIVEN that I am looking at the Connect Wallet modal
WHEN I click cancel
THEN the modal closes

GIVEN that I am looking at the Connect Wallet modal
WHEN I click "Connect Wallet"
THEN the modal stays open
AND I am prompted to connect my wallet

GIVEN that I have clicked Connect Wallet
WHEN I finish connecting my wallet
THEN the modal closes
AND the donation process continues

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1583%3A56446)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Moving this to blocked cause i think this would need to happen before the balance check as we would need the balance.

**Comment by nfrgosselin** [comment]
@thelostone-mc good call! Just chatted with @melissa-neira — let's skip our modal and just bring up the rainbowkit connect modal when they click on submit but haven't connected their wallet. Does that work?

**Comment by thelostone-mc** [comment]
Yup that works
