### ISSUE TITLE
follow-on subgraph story

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#653]
address comments from #532 

**User Story:**
As a
I want to
So that

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
Closing this out as stories are already created
