### ISSUE TITLE
Make project titles & project photos clickable in Donation Builder

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-round#691]
**User Story:**
As a user
I want to check out more about a project I've put into my Shortlist and/or Final Donation
So that I can learn more about a project/reference it again

**Acceptance Criteria**
GIVEN that a project is in the Shortlist or Final Donation box
WHEN a user hovers on the **project photo**
THEN the user sees a "view project" icon and can click on it to go to the project details page

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1957%3A82840)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by hmrtn** [comment]
Can we actually use a seperate button on the shortlist/final ballot that points directs the user to the project page? 

Having them select the title or picture interferes with the selection process for moving the project from shortlist to final/

**Comment by hmrtn** [comment]
^ something like "view project" next to the trash icon?

**Comment by melissa-neira** [comment]
@hmrtn good call out! sure, let me play with the design a bit and I'll update the AC
