### ISSUE TITLE
Integrate Price Oracle for round stats

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#706]
**User Story:**
As a round data consumer
I want to see total donations in USD
So that I can normalize results

**Acceptance Criteria**
GIVEN
WHEN
THEN

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by thelostone-mc** [comment]
The goal here is to build a util function within the api package which 

- talks to an external API to define the price oracle.
- given a from and to token -> it gives back the conversion rate

With this in place -> after all the contribution is fetched
We invoke this util function to convert all the contribution into the same token as the round token before running the calculations

**Comment by vacekj** [comment]
For the API: we can use CoinMarketCap API, they even have some form of Free API Sponsorship here: https://coinmarketcap.com/alexandria/article/join-coinmarketcap-s-new-free-api-scholarship-program, looks like it's targeted at individuals but I think we could form a partnership regardless. Another option is CoinGecko, which has a very generous free tier: https://www.coingecko.com/en/api/pricing. Will go with CoinGecko for now and we can talk to CMC later.

**Comment by chibie** [comment]
in other to use a third-party price converter, do we need to have a db table for tokens?

since we will need the token symbol for conversion

@thelostone-mc

**Comment by vacekj** [comment]
Don't need a db rn, caching is more of a v2 function.
