### ISSUE TITLE
New applications showing 404

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#733]
**Overview**
Fantom has reported that they're seeing 404 when they look at new applications in RM (even though they can still see the old applications). Their note: "I’ve started getting a 404 error when I click on a new applicants proposal, just started happening yesterday. See SS’s (1st one the applications , second if i click on any new application)"

**Screenshots**
![2022-12-02 08 50 47](https://user-images.githubusercontent.com/15041635/205308373-3926be75-a146-4f14-a3e7-3fcf44959055.jpg)
![2022-12-02 08 51 04](https://user-images.githubusercontent.com/15041635/205308387-8718e92f-9a21-4028-a966-548acdb5922f.jpg)

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by vacekj** [comment]
Here's a new application tx that I think is affected: https://ftmscan.com/tx/0x152663b1af8cc72a9ad42ebb31b87f301626a2f252502ad5ec3fca6d5fcd2fa8
Here's the IPFS link to the application (from the tx): bafkreibaztacg33mfcxa7tc6bzmkmxyfhqhneibazu3g3pnt5c7qho3e4e
It's not loading for me on any gateway nor my local IPFS node, so my first guess is that Piňata is not Piňatting our IPFS files 😤

**Comment by kevinrolsen** [comment]
I'm seeing the data here: https://api.ipfsbrowser.com/ipfs/get.php?hash=bafkreibaztacg33mfcxa7tc6bzmkmxyfhqhneibazu3g3pnt5c7qho3e4e

**Comment by vacekj** [comment]
Interesting, then maybe pinata is not serving it right. Can you try this link on your device please? https://gitcoin.mypinata.cloud/ipfs/bafkreifbn6dnrenfqkcohn6qfrlixnv5ma2v2rnib6fnjjjrkp74rfgx2a?preview=1

**Comment by vacekj** [comment]
Might've been a pinata issue after all, links are working for me and Hans now. Melissa pinged the Fantom team to kindly re-try.

**Comment by kevinrolsen** [comment]
Ok yah, I'm seeing the data now on pinata. Might be worth giving pinata support a ping to see if there's anything we can be monitoring in situations like this?

**Comment by vacekj** [comment]
@thelostone-mc do we have a direct contact for Pinata?

**Comment by vacekj** [comment]
error Error: invalid BigNumber string (argument="value", value="250:0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174:111", code=INVALID_ARGUMENT, version=bignumber/5.7.0)

happening on 
https://round-manager.gitcoin.co/#/round/0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3/application/0x8bbbc891b96e11a578be3e6d6cc94d6a63730bf3d7d236e1db482d2339f42a75-0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3

**Comment by vacekj** [comment]
ProjectRegistry (GrantHub) addy: 0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174
Project IDs: 111 and 108

**Comment by thelostone-mc** [comment]
We've made some progress. Following up with the hub team cause it looks like application Id format has changed
https://discord.com/channels/562828676480237578/962026258273804398/1048316388558782495

**Comment by DanieleSalatti** [comment]
We modified the way we pass the id around within grant-hub, but we were trying to not change format for applications and IPFS.

Looks like we missed something in our changes and we are now sending out a different format for project id on IPFS...

Following up on Discord at the above thread, will post updates here.
