### ISSUE TITLE
UI clean up - heads up modal

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-round#762]
Modal currently looks like this (the icon on the top left corner is squished)
<img width="558" alt="Screen Shot 2022-12-07 at 12 25 16" src="https://user-images.githubusercontent.com/87520659/206200590-31de8c42-384f-4fda-98eb-4c1e681cbcc4.png">

**Acceptance Criteria**
- Circle should be 40x40 px
- [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1987%3A54401&t=9O9IM3rQkRZWNL3C-4)

**Comment by thelostone-mc** [comment]
Looks like this is already resolved in main.
Closing this out 


![Image](https://user-images.githubusercontent.com/5358146/206386566-8ba20cba-ce63-49ce-a509-196405153ca7.png)
