### ISSUE TITLE
Intermittent error on shortlist selection

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#787]
**Overview**
I'm getting an intermittent error when I try to individually select projects from the shortlist and move them to the final donation. The loom shows several different attempts (the last one fails), but it seems like I can reproduce the error when I have a wallet connected and hard refresh the donation page.

**Observed  behavior**
When I click to add selected, all the projects deselect (as if it was successful) but nothing moves. 

**Expected behavior**
The projects should move to the final donation 

**Screenshots**
[Loom video](https://www.loom.com/share/b5ffa1f560c84d3c89f5d1f73fcc3e90)

**Comment by thelostone-mc** [comment]
Not able to reproduce this at my end 😓

**Comment by chibie** [comment]
@thelostone-mc i was able to reproduce, you have to clear cache

**Comment by chibie** [comment]
@thelostone-mc so i cleared my local storage and the error no longer happens.

@nfrgosselin can you follow the instructions here https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/ to clear yours and let us know if you still get the error?

**Comment by nfrgosselin** [comment]
Hmmm I can't seem to reproduce this anymore. I'm going to close.

Thanks for looking at it @chibie
