### ISSUE TITLE
GE- Responsive landing page: project cards, nav bar, header

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-round#805]
**Overview**
- Nav bar: nav bar is not responsive when viewport is at 375x667
- Header + description: alignment is too narrow
- Search bar is not responsive
- Project cards: cards vary in width and look kinda crazy

**Steps To Reproduce**
1. Go to GE landing page
2. View page at 375x667
3. Scroll around

**Observed  behavior**
- Nav bar is misaligned
- Round name and description is too narrow, should be wider
- Search bar is too wide
- Project cards all vary in width

**Expected behavior**
Should look along the lines of this - [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1680%3A51032&t=5AUz632hzlgwHbml-4)

**Screenshots**
Long screen shot coming your way:
![screencapture-grant-explorer-gitcoin-co-2022-12-09-19_07_24](https://user-images.githubusercontent.com/87520659/206766481-a2f1da78-45fe-46cd-bdac-919a78ca0121.png)

**Comment by thelostone-mc** [comment]
Many of these are fixed. Would be worth taking a look at this with the latest changes and updating this ticket @melissa-neira
