### ISSUE TITLE
Approved project not showing in round

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#823]
**Overview**
[This project](https://grantshub.gitcoin.co/#/chains/250/registry/0x8e1bD5Da87C14dd8e08F7ecc2aBf9D1d558ea174/projects/47) sees that they are approved for the Fantom round in Grant Hub, but the project is not showing up on the [round's Grant Explorer](https://grant-explorer.gitcoin.co/#/round/250/0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3) or in Round Manager.

**Comment by hmrtn** [comment]
This was resolved. By default, The graph was limiting the response of projects to 100, per request. 

We resolved this by maxing out the req to 1000 - meaning it will still be problem when a round contains > 1000 projects. We will need to change this to pagination, when it is a problem. 
See here for more info:
https://thegraph.com/docs/en/developing/developer-faqs/#23-is-there-a-limit-to-how-many-objects-the-graph-can-return-per-query
