### ISSUE TITLE
API bugs

### ISSUE THREAD

**Issue by bhargavaparoksham** [gitcoinco/grants-round#836]
API bugs that needs to be resolved.

1. calling calculate api call for the unicef round gives the below error, - @chibie 
https://user-images.githubusercontent.com/22616592/207359599-55f3f430-248f-4502-ad5b-58b70b836e64.png

2. calling /project-stats  api call for the fantom round with a valid project fails. - @thelostone-mc 
API call : 
`http://localhost:8000/project-stats?roundId=0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3&chainId=250&projectId=0x87f385d152944689f92ed523e9e5e9bd58ea62ef`

```json
{
    "success": false,
    "message": "error: something went wrong.",
    "data": {}
}
```

3. API feature needed: calling `/round-stats` api call gives overall round stats.
 We need a call that gives out all projects & their respective contributor stats.  @bhargavaparoksham + @vacekj

**Comment by bhargavaparoksham** [comment]
@thelostone-mc figured out why the issue 2 is happening while working on 3. Pushing the fix for 2 in our PR. fyi

**Comment by hmrtn** [comment]
Is this PR pushed?

**Comment by hmrtn** [comment]
@chibie Do you have the mainnet subgraph api in your env?

**Comment by hmrtn** [comment]
Looks like issue #2 has to do with a missing `$` on the `projectId` parameter in `fetchVotesForProjectInRoundHandler`.

**Comment by bhargavaparoksham** [comment]
@hmrtn here's the draft pr, https://github.com/gitcoinco/grants-round/pull/841
