### ISSUE TITLE
Replace IPFS with contract call for approved projects

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#845]
#### Description 

Currently, the API package uses fetches approved projects from the graph which is not stable  
The goal here is to rely on the projectMetaPtr hash from the round contract and then populate the list of approved projects.
This changes are already implemented in round manager and can be borrowed from there

**Comment by thelostone-mc** [comment]
Closing this out as given the current implementation. This doesn't seem to be required
