### ISSUE TITLE
Download matching JSON

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#866]
**User Story:**
As a round operator
I want to finalize and store my fund distribution
So that my round results are public and verifiable

**Acceptance Criteria**
GIVEN that I am on the Funding Admin tab after my round has ended
WHEN I click the Download JSON button
THEN the JSON file is downloaded to my machine

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=3333%3A45810&t=AJekSKSzpyWU5TFj-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
@bhargavaparoksham I probably missed the conversation around this, but is this a WIP, should I finalize it?

**Comment by bhargavaparoksham** [comment]
@vacekj yes, if you are working today, please take it forward, if not i'll continue with it tomorrow.
