### ISSUE TITLE
Add Finalize round toggle

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#867]
**User Story:**
As a round operator
I want to finalize and store my fund distribution
So that my round results are public and verifiable

**Acceptance Criteria**
GIVEN that I am on the Funding Admin tab after my round has ended
WHEN I look below the Download JSON button
THEN I see a toggle to select default or upload my own json
AND the default radial button is selected

GIVEN that I am on the Funding Admin tab after my round has ended
WHEN I click on the upload my own radial button
THEN I see the upload section

GIVEN that I am on the Funding Admin tab after my round has ended and have Upload My Own selected
WHEN I click on the default radial button
THEN the Upload section disappears

**Product & Design Links:**
[Figma](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=3519%3A49180&t=cdEqlYuPoK2gd0TW-4)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by melissa-neira** [comment]
@bhargavaparoksham link has been updated 😎
