### ISSUE TITLE
bug: fetch project votes by project registry id

### ISSUE THREAD

**Issue by hmrtn** [gitcoinco/grants-round#919]
**Overview**
There is a bug in the API package when using the update project summary post endpoint. 

It was built to use project addresses to index the graph and database. 

It needs to be refactored to utilize the project-id, just as in the frontend application.

**Comment by thelostone-mc** [comment]
I just tried 

http://localhost:8000/api/v1/update/summary/project/1/0xdf75054cd67217aee44b4f9e4ebc651c00330938/0xc03062b43ed99ac4e560c62adf52960a21df6f09b80b82841f35ba0cd7f6cc27

http://localhost:8000/api/v1/data/summary/project/1/0xdf75054cd67217aee44b4f9e4ebc651c00330938/0xc03062b43ed99ac4e560c62adf52960a21df6f09b80b82841f35ba0cd7f6cc27

And it seems to work. Has this already been fixed ?

![Image](https://user-images.githubusercontent.com/5358146/212820253-feca1de8-b1f3-4d8e-a730-621b0bc05120.png)

**Comment by nfrgosselin** [comment]
@thelostone-mc @hmrtn is this bug complete? I don't see a PR on it

**Comment by nfrgosselin** [comment]
Closing per my chat with @hmrtn
