### ISSUE TITLE
task: get test coverage to 100% on RoundImplementation

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#92]

**Comment by thelostone-mc** [comment]
![Image](https://user-images.githubusercontent.com/5358146/177299495-4605845b-673b-4de7-bee7-470896b8838a.png)


![Image](https://user-images.githubusercontent.com/5358146/177299583-36542d74-f7c8-4dae-b730-cb27a7c0fce2.png)
