### ISSUE TITLE
chore: run tests with tsc

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#949]
### Description

- [x] Remove tests from running in pre-commit
- [x] Update tests in all packages to use tsc as this runs faster
  - [x] api 
  - [x] grants-round
  - [x] round-manager
- [x] Update CI to also use tsc which are faster

Ref: https://github.com/gitcoinco/grants-round/discussions/853

**Comment by vacekj** [comment]
Resolved in #929
