### ISSUE TITLE
feat: display content from Hub WYSIWYG editor

### ISSUE THREAD

**Issue by chibie** [gitcoinco/grants-round#973]
### Description

Wire in markdown rendering for the following components:

**Round Manager**
- [x] Page where you can review an individual project application
- [x] Page where you can review all project applications

**Grant Explorer**
- [x] Page where you can review an individual project taking part in the round
- [x] Page where you can review all projects in the round
- [x] Page where you cast your donations

Additionally:
- [x] Use Tailwind Typograhy and mark those components as prose to get nice formatting for free

**Comment by thelostone-mc** [comment]
This task requires pairing with @boudra and implement the same feature as https://github.com/gitcoinco/grant-hub/pull/698
