### ISSUE TITLE
feat: update the recalculate score flow for new API 

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#974]
### Description

Read this section on how to make these changes:
https://discord.com/channels/562828676480237578/1042785636333146204/1063022368840232981

Passport has updated how their submit score endpoint works and it's now an async process!
We would now have to ensure that we keeping fetching the score until the status is DONE. 
Additionally the threshold is also provided by the get score endpoint

**Comment by thelostone-mc** [comment]
Review on https://github.com/gitcoinco/grants-round/pull/982

**Comment by nfrgosselin** [comment]
This looks good to me — moving to staging
