### ISSUE TITLE
Passport verification page updates

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-round#977]
**Acceptance Criteria**
The page looks pretty much the same as before, but without tabs. Copy has been updated as well.  [Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=2951%3A79342&t=hbYikfSTcCn84J6z-4)
- No more tabs
- Updated copy
- Added link for support ("need help" button on the bottom) - I don't have a link for this yet, I should be receiving something soon from the support team.

**Comment by thelostone-mc** [comment]
Review on https://github.com/gitcoinco/grants-round/pull/982

**Comment by nfrgosselin** [comment]
Accepting this on behalf of @melissa-neira so we can get this in for the production release
