### ISSUE TITLE
Change Invalid Passport language

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#983]
**Details**
The current "Invalid Passport" banner language is misleading, as it sounds like the user has an error if they don't have their Passport set up. We want to change the language.

**Acceptance Criteria**
GIVEN that the user has connected their wallet
WHEN the Passport API returns a 400 error
THEN the banner reads "Passport score not detected. Please configure your Passport."
AND "Please configure your passport" is a link to the Explorer's Passport verification page

**Product & Design Links:**

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by vacekj** [comment]
@nfrgosselin currently we have the InvalidPassportButton there, that leads to the passport configuration for the given round, with the text Visit Passport. Should I leave that in, and just replace the text?
