### ISSUE TITLE
bug: Passport call erroring out

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#997]
**Overview**
When I open the Explorers for the Grants Alpha rounds I either get a continuous loading or an error.

**Steps To Reproduce**
On this [Explorer](https://grant-explorer.gitcoin.co/#/round/1/0xe575282b376e3c9886779a841a2510f1dd8c2ce4) I got an error:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/15041635/212909869-9d3dba94-f52e-479d-8796-737769627209.png">

On this [Explorer](https://grant-explorer.gitcoin.co/#/round/1/0x1b165fe4da6bc58ab8370ddc763d367d29f50ef0) I'm stuck in the spinny wheel of death
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/15041635/212910011-38cc6430-c611-4c79-9ed1-dd5b1c1b0303.png">

**Comment by thelostone-mc** [comment]
This was due to passport service being down
